"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { AppGlyph, ClientMark } from "./VisualIdentity";
import { projectApps, type WorkspaceProject } from "./workspace-model";
import { getOsCaseEvidence, osEvidenceFetchedOn } from "./os-case-evidence";
import SimulationStudio, { downloadJson, persistSimulationRun, moneyLabel, numberLabel, simulationDefaults, SimulationResults } from "./SimulationStudio";
import { restoreSimulation, runSimulation, simulationStorageKey, type SimulationRun } from "./simulation-model";
import { collectorManifest, createSourceDraft, emptyOsProject, evaluateSkill, ingestSample, osStorageKey, recordFeedback, restoreOsProject, serializeOsProject, scheduleWorkers, type OsProjectState, type SourceDraft } from "./agent-os-model";
import "./agent-os.css";

type Section = "missions" | "connections" | "intelligence" | "tools" | "learning";
const sections: { id: Section; icon: string; name: string }[] = [{ id: "missions", icon: "◎", name: "Missions" }, { id: "connections", icon: "⇄", name: "Connections" }, { id: "intelligence", icon: "◈", name: "Intelligence" }, { id: "tools", icon: "⌘", name: "Tools" }, { id: "learning", icon: "↗", name: "Learning" }];
const phases = ["Load project snapshot", "Validate evidence boundary", "Compute paired simulation", "Compare cost and service", "Evaluate review gates"];
function projectHref(projectId: string, appId?: string) {
  if (!appId) return `/?view=company&project=${encodeURIComponent(projectId)}&projectTab=overview`;
  if (appId === "playground") return `/?view=company&project=${encodeURIComponent(projectId)}&projectTab=agents`;
  return ["risk", "optimizer", "flow", "demand", "suppliers"].includes(appId) ? `/?view=${appId}&project=${encodeURIComponent(projectId)}` : `/?view=company&project=${encodeURIComponent(projectId)}&projectTab=apps&projectApp=${appId}`;
}
export default function AgentOS({ projects }: { projects: readonly WorkspaceProject[] }) {
  const [projectId, setProjectId] = useState(projects[0]?.id ?? "");
  const [section, setSection] = useState<Section>("missions");
  useEffect(() => { const hydration = window.setTimeout(() => { const params = new URLSearchParams(window.location.search); const id = params.get("osProject"); if (id && projects.some((project) => project.id === id)) setProjectId(id); const tab = params.get("osSection"); if (sections.some((item) => item.id === tab)) setSection(tab as Section); }, 0); return () => window.clearTimeout(hydration); }, [projects]);
  const project = projects.find((item) => item.id === projectId) ?? projects[0];
  if (!project) return <section className="agent-os os-empty"><h2>No accessible projects</h2><p>Create a client project before starting a mission.</p></section>;
  const select = (id: string, tab: Section = section) => { setProjectId(id); setSection(tab); const url = new URL(window.location.href); url.searchParams.set("osProject", id); url.searchParams.set("osSection", tab); window.history.replaceState(window.history.state, "", url); };
  return <div className="agent-os">
    <header className="os-top"><div><h1 data-page-heading tabIndex={-1}>Mission control</h1><span>Supply chain agent OS</span></div><label className="os-client"><ClientMark clientId={project.clientId} label={project.client} /><select aria-label="Mission client and project" value={project.id} onChange={(event) => select(event.target.value)}>{projects.map((item) => <option key={item.id} value={item.id}>{item.client} / {item.name}</option>)}</select></label><a href={projectHref(project.id, "playground")}>Open terminal ↗</a></header>
    <nav className="os-tabs" aria-label="Agent OS sections">{sections.map((item) => <button type="button" key={item.id} className={section === item.id ? "active" : ""} aria-current={section === item.id ? "page" : undefined} onClick={() => select(project.id, item.id)}><span aria-hidden="true">{item.icon}</span>{item.name}</button>)}<a href="/tanjnx-user-guide.pptx" download>How to use ↓</a></nav>
    <OsProject key={project.id} project={project} section={section} onSection={(tab) => select(project.id, tab)} />
  </div>;
}

function OsProject({ project, section, onSection }: { project: WorkspaceProject; section: Section; onSection: (section: Section) => void }) {
  const evidence = getOsCaseEvidence(project.id);
  const [state, setState] = useState<OsProjectState>(emptyOsProject);
  const [hydrated, setHydrated] = useState(false);
  const [run, setRun] = useState<SimulationRun | null>(null);
  const [phase, setPhase] = useState(-1);
  const [selectedPhase, setSelectedPhase] = useState(0);
  const [notice, setNotice] = useState("");
  const [reviewNote, setReviewNote] = useState("");
  const [reviewedRun, setReviewedRun] = useState("");
  const [sourceKind, setSourceKind] = useState<SourceDraft["kind"]>("Desktop agent");
  const [sourceName, setSourceName] = useState("");
  const [allowlist, setAllowlist] = useState("");
  const [consent, setConsent] = useState(false);
  const [deviceId, setDeviceId] = useState("");
  const [selectedSource, setSelectedSource] = useState("");
  const [payload, setPayload] = useState("");
  const [observed, setObserved] = useState(95);
  const [outcomeNote, setOutcomeNote] = useState("");
  const [sourceQuery, setSourceQuery] = useState("");
  const [toolId, setToolId] = useState("simulation");
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const running = phase >= 0 && phase < phases.length;
  useEffect(() => {
    const hydration = window.setTimeout(() => {
    try {
      setState(restoreOsProject(localStorage.getItem(osStorageKey(project.id)), project.id));

      const savedRun = restoreSimulation(localStorage.getItem(simulationStorageKey(project.id)), project.id); setRun(savedRun); if (savedRun) setPhase(phases.length);
    } catch { setNotice("Saved local state could not be restored. This session starts with a clean workspace."); }
    setHydrated(true); 
    }, 0);
    return () => { window.clearTimeout(hydration); if (timer.current) clearTimeout(timer.current); };
  }, [project.id]);
  useEffect(() => { if (hydrated) try { localStorage.setItem(osStorageKey(project.id), serializeOsProject(state, project.id)); } catch { /* Session remains fully usable without persistence. */ } }, [state, hydrated, project.id]);
  useEffect(() => { if (section === "missions") return; if (timer.current) clearTimeout(timer.current); const cancelled = window.setTimeout(() => setPhase((current) => current >= 0 && current < phases.length ? -2 : current), 0); return () => window.clearTimeout(cancelled); }, [section]);
  if (!evidence) return <div className="os-empty"><b>Prepare this project’s first mission</b><p>Publish a scoped data contract in Data, then define its simulation and review criteria.</p><a href={`/?view=company&project=${project.id}&projectTab=data`}>Open project Data</a></div>;
  const log = (message: string) => { setNotice(message); setState((current) => ({ ...current, activity: [`${new Date().toISOString()} ${message}`, ...current.activity].slice(0, 30) })); };
  const saveRun = (result: SimulationRun) => { setRun(result); setReviewedRun(""); try { persistSimulationRun(result); } catch { log("Run calculated; export it because browser storage is unavailable."); } };
  const start = () => {
    if (running) return;
    const input = run?.input ?? simulationDefaults(project.id);
    if (!input) return;
    setPhase(0); setSelectedPhase(0); setReviewedRun("");
    const advance = (step: number) => {
      if (step === 2) { try { saveRun(runSimulation(input)); } catch (error) { setPhase(-1); log(String(error)); return; } }
      setPhase(step); setSelectedPhase(Math.min(step, phases.length - 1));
      if (step < phases.length) timer.current = setTimeout(() => advance(step + 1), 450);
      else log("Mission replay completed. Review the calculated result and unresolved domain gates.");
    };
    timer.current = setTimeout(() => advance(1), 450);
  };
  const stop = () => { if (timer.current) clearTimeout(timer.current); setPhase(-2); log("Replay stopped. Completed artifacts are retained; no external worker was running."); };
  const addSource = () => {
    try { const draft = createSourceDraft({ projectId: project.id, kind: sourceKind, name: sourceName, allowlist, approved: consent, deviceId: sourceKind === "IoT device" ? deviceId : undefined, min: sourceKind === "IoT device" ? 2 : undefined, max: sourceKind === "IoT device" ? 8 : undefined }); setState((current) => ({ ...current, sources: [...current.sources, draft] })); setSelectedSource(draft.id); setSourceName(""); setConsent(false); log("Connection profile saved locally. No agent installed, device enrolled, or source contacted."); } catch (error) { log(error instanceof Error ? error.message : "Unable to create profile."); }
  };
  const source = state.sources.find((item) => item.id === selectedSource);
  const skill = evaluateSkill(state.feedback);
  const tool = projectApps.find((item) => item.id === toolId) ?? projectApps[0];
  return <>
    <div className="os-boundary"><span>Interactive rehearsal</span><small>Public evidence checked {osEvidenceFetchedOn}. Private operations modeled. No background agent, live feed, or write-back connected.</small></div>
    {notice && <div className="os-notice" role="status"><span>{notice}</span><button type="button" aria-label="Dismiss notice" onClick={() => setNotice("")}>×</button></div>}
    {section === "missions" && <>
      <div className="os-command"><div><small>PRIORITY MISSION</small><b>{evidence.decisionQuestion}</b></div>{running ? <button type="button" onClick={stop}>Stop replay</button> : <button className="os-primary" type="button" onClick={start}>{run ? "Rerun mission" : "Run mission"}</button>}<button type="button" onClick={() => { setToolId("simulation"); onSection("tools"); }}>Challenge assumptions</button></div>
      <div className="os-mission-grid"><section className="os-panel"><header><h2>Situation brief</h2><a href={projectHref(project.id)}>Open project ↗</a></header><p>{evidence.scenarioNarrative}</p><div className="os-facts">{evidence.publicContext.map((fact) => <div key={fact.sourceId}><small>PUBLIC FACT · {fact.asOf}</small><p>{fact.fact}</p><a href={evidence.sources.find((s) => s.id === fact.sourceId)?.url} target="_blank" rel="noreferrer">Source ↗</a></div>)}</div><details><summary>{evidence.hardConstraints.length} domain constraints requiring expert verification</summary><ul>{evidence.hardConstraints.map((constraint) => <li key={constraint}>{constraint}</li>)}</ul><p className="os-help">These gates are not evaluated by the aggregate simulator. A passing service or budget check cannot override them.</p></details></section>
        <section className="os-panel os-trace"><header><h2>Execution trace</h2><small>{running ? "Replaying workflow" : phase === -2 ? "Replay stopped" : run ? run.id : "Ready"}</small></header>{phases.map((name, index) => <button type="button" key={name} className={selectedPhase === index ? "active" : ""} onClick={() => setSelectedPhase(index)}><span>{running && index === phase ? "◌" : (running && index < phase) || phase === phases.length ? "✓" : phase === -2 ? "—" : String(index + 1).padStart(2, "0")}</span><b>{name}</b><small>{index === 2 ? "Simulation tool" : "Local workflow"}</small></button>)}<div className="os-trace-detail"><b>{phases[selectedPhase]}</b><p>{[`${project.code} · ${evidence.scenario.unit} · ${evidence.scenario.horizonWeeks}-week horizon. The input snapshot is project-scoped.`, `${evidence.sources.length} public sources, ${evidence.scenario.operationalInputs.length} domain assumptions, ${state.events.filter((event) => event.disposition === "quarantined").length} quarantined sample events. Public context never becomes a private company observation.`, run ? `${run.input.paths} paired paths using ${run.version}. Seed ${run.input.seed}. Service mean ${numberLabel(run.response.service.mean)}%.` : "Computes a Markov-state shipment pipeline and triangular demand for each replication; no LLM or external solver invoked.", run ? `Net mean loss avoided ${moneyLabel(run.protectedLoss)}. Tail loss ${moneyLabel(run.response.cvar95)}. Full inputs and result export remain available.` : "Compare response with baseline under identical exogenous draws.", run ? `P05 service check ${run.targetPassed ? "passed" : "failed"}; budget check ${run.budgetPassed ? "passed" : "failed"}. Domain review remains open.` : "Service, budget and domain review gates remain open."][selectedPhase]}</p>{run && <button type="button" onClick={() => downloadJson(run, `${run.id}.json`)}>Export full calculated artifact ↓</button>}</div></section></div>
      {run && <><SimulationResults run={run} /><section className="os-panel os-review"><div><h3>Human checkpoint</h3><p>Record a review note against this exact run. Production release is unavailable.</p></div><input aria-label="Review rationale" placeholder="What needs validation before action?" value={reviewNote} onChange={(event) => setReviewNote(event.target.value)} /><button type="button" disabled={reviewNote.trim().length < 12 || running} onClick={() => { setReviewedRun(run.id); log(`Review note recorded for ${run.id}: ${reviewNote.trim()}`); }}>{reviewedRun === run.id ? "Note recorded" : "Record review note"}</button></section></>}
      <section className="os-panel"><header><h3>Specialist worker plan</h3><label>Concurrent slots<select value={state.workerLimit} onChange={(event) => setState({ ...state, workerLimit: Number(event.target.value) })}>{[1,2,3,4,5,6].map((n) => <option key={n}>{n}</option>)}</select></label></header><div className="os-workers">{scheduleWorkers(state.workerLimit, running).map((worker) => <div key={worker.id}><b>{worker.role}</b><span data-state={worker.state}>{worker.state === "expired" ? "Lease released" : worker.state}</span><small>15-minute proposed lease · project-read / artifact-write</small></div>)}</div><p className="os-help">Scheduling preview: slots and queue respond to the selected limit. No processes or autonomous temporary agents are spawned.</p></section>
    </>}
    {section === "connections" && <div className="os-connect-grid"><section className="os-panel"><header><h2>Connection setup</h2><small>Permission first</small></header><p>A local companion should combine approved data collection and terminal chat. This portal prepares the policy; installation requires the production enrollment service.</p><div className="os-form-grid"><label>Connection type<select value={sourceKind} onChange={(event) => setSourceKind(event.target.value as SourceDraft["kind"])}><option>Desktop agent</option><option>Enterprise API</option><option>IoT device</option></select></label><label>Profile name<input value={sourceName} onChange={(event) => setSourceName(event.target.value)} placeholder="e.g. Approved planning exports" /></label><label className="os-wide">Exact allowed folders, tables, or topics<input value={allowlist} onChange={(event) => setAllowlist(event.target.value)} placeholder={sourceKind === "IoT device" ? "site-a/coldroom-1/temperature" : "C:\\Planning\\approved-exports"} /></label>{sourceKind === "IoT device" && <label>Device identifier<input value={deviceId} onChange={(event) => setDeviceId(event.target.value)} placeholder="TEMP-SITE-A-001" /></label>}<label className="os-checkbox os-wide"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} />I have approval to prepare this read-only scope.</label></div><button type="button" className="os-primary" onClick={addSource}>Save connection profile</button><details><summary>Production enrollment requirements</summary><ul><li>Signed installer and tenant-bound short-lived pairing token.</li><li>Outbound mTLS, per-source allowlist and encrypted offline buffer.</li><li>Redaction before upload, schema checks, replay checkpoints and revocation.</li><li>Same local CLI for chat, mentions and tools, with approval before sensitive actions.</li></ul><p className="os-help">Do not enter credentials here. The exported draft contains no executable installation command or enrollment token.</p></details></section>
      <section className="os-panel"><header><h2>Connection profiles</h2><small>{state.sources.length} local drafts</small></header>{state.sources.length ? state.sources.map((item) => <div className="os-source-row" key={item.id}><button type="button" onClick={() => setSelectedSource(item.id)} className={selectedSource === item.id ? "active" : ""}><b>{item.name}</b><small>{item.kind} · {item.allowlist}</small></button><label className="os-checkbox"><input type="checkbox" checked={item.enabled} onChange={(event) => setState({ ...state, sources: state.sources.map((s) => s.id === item.id ? { ...s, enabled: event.target.checked } : s) })} />Sample enabled</label><button type="button" onClick={() => downloadJson(collectorManifest(item), `${item.id}.json`)}>Export policy</button></div>) : <div className="os-empty"><b>No sources connected</b><p>Create a scoped profile to explore the approval and ingestion workflow.</p></div>}
      {source?.kind === "IoT device" && <section className="os-telemetry"><h3>Device sample validator</h3><p className="os-help">Temperature example, 2–8°C. No actual sensor connection or product-specific storage instruction.</p><button type="button" onClick={() => setPayload(JSON.stringify({ id: `EV-${Date.now()}`, deviceId: source.deviceId, sequence: Math.max(0, ...state.events.filter((e) => e.deviceId === source.deviceId && e.disposition === "accepted").map((e) => e.sequence)) + 1, observedAt: new Date().toISOString(), value: 5.1, unit: "°C" }, null, 2))}>Prepare editable sample</button><textarea rows={6} aria-label="Device event JSON" value={payload} onChange={(event) => setPayload(event.target.value)} /><button type="button" disabled={!source.enabled} onClick={() => { try { const event = ingestSample(source, state.events, payload); setState({ ...state, events: [event, ...state.events].slice(0, 100) }); log(`${event.id}: ${event.disposition}. ${event.reason}`); } catch (error) { log(error instanceof Error ? error.message : "Invalid sample"); } }}>Validate sample event</button></section>}
      <details><summary>Ingestion ledger ({state.events.length})</summary>{state.events.map((event) => <div className="os-ledger-row" key={event.id}><code>{event.id}</code><b>{event.value}{event.unit} · {event.disposition}</b><span>{event.reason}</span><small>{event.observedAt} → {event.receivedAt}</small></div>)}</details></section></div>}
    {section === "intelligence" && <>
      <div className="os-command"><div><b>Evidence and operating context</b><span>Client-private knowledge and platform-public intelligence retain separate provenance.</span></div><input aria-label="Search public sources" placeholder="Find a source or fact…" value={sourceQuery} onChange={(event) => setSourceQuery(event.target.value)} /><a href={`/?view=company&project=${project.id}&projectTab=data`}>Project knowledge graph ↗</a><Link href="/?view=global">World graph ↗</Link></div>
      <section className="os-panel"><header><h2>Public source register</h2><small>Retrieved {osEvidenceFetchedOn} · no live refresh</small></header>{evidence.sources.filter((item) => `${item.title} ${item.freshnessNote}`.toLowerCase().includes(sourceQuery.toLowerCase())).map((item) => <article className="os-source-evidence" key={item.id}><a href={item.url} target="_blank" rel="noreferrer">{item.title} ↗</a><span>Published {item.publishedOn ?? "not stated"} · describes {item.asOf}</span><p>{item.freshnessNote}</p></article>)}</section>
      <div className="os-results-grid"><section className="os-panel"><header><h3>Signals to connect</h3><small>Target refresh cadence</small></header>{evidence.monitoredSignals.map((signal) => <p className="os-signal" key={signal}>{signal}</p>)}<button type="button" onClick={() => onSection("connections")}>Prepare source permissions</button></section><section className="os-panel"><header><h3>Domain planning inputs</h3><small>Modeled assumptions</small></header><table className="os-table"><thead><tr><th>Input</th><th>Value</th><th>Interpretation</th></tr></thead><tbody>{evidence.scenario.operationalInputs.map((item) => <tr key={item.label}><th>{item.label}</th><td>{numberLabel(item.value)} {item.unit}</td><td>{item.meaning}</td></tr>)}</tbody></table><p className="os-help">Domain inputs inform the case brief. They are not automatically enforced in the aggregate Simulation model.</p></section></div>
    </>}
    {section === "tools" && <>
      <div className="os-tool-strip" role="group" aria-label="Agent tools">{projectApps.filter((item) => project.mountedAppIds.includes(item.id)).map((item) => <button type="button" key={item.id} className={tool.id === item.id ? "active" : ""} onClick={() => setToolId(item.id)}><AppGlyph appId={item.id} /><span>{item.name}</span></button>)}</div>
      {tool.id === "simulation" ? <SimulationStudio key={project.id} projectId={project.id} onRun={saveRun} /> : <section className="os-panel"><header><h2>{tool.name}</h2><a className="os-primary" href={projectHref(project.id, tool.id)}>Open tool ↗</a></header><p>{tool.outcome}</p><dl className="os-contract"><div><dt>Input contract</dt><dd>{tool.variableIds.join(", ")}</dd></div><div><dt>Methods</dt><dd>{tool.methodCodes.join(", ")}</dd></div><div><dt>Output artifact</dt><dd>{tool.artifact}</dd></div><div><dt>Execution boundary</dt><dd>Existing interactive workbench. Tool deployment, researcher validation and a live agent adapter remain separate.</dd></div></dl><p className="os-help">Agents should call a versioned tool contract; users open the same artifact to inspect inputs, rerun and challenge assumptions. The Simulation tool in this workspace executes the new browser calculation; opening another tool preserves project context.</p></section>}
      <details className="os-panel"><summary>Recommended analytical sequence for {project.client}</summary><ol>{evidence.toolSequence.map((step) => <li key={step}>{step}</li>)}</ol></details>
    </>}
    {section === "learning" && <div className="os-connect-grid"><section className="os-panel"><header><h2>Outcome feedback</h2><small>Project-isolated</small></header><p>Compare a frozen prediction with a measured outcome. Here, entered outcomes are rehearsal records, not verified company performance.</p>{run ? <><p>Run <code>{run.id}</code> predicted mean service {numberLabel(run.response.service.mean)}%.</p><label>Observed service (%)<input type="number" min="0" max="100" step="0.1" value={Number.isFinite(observed) ? observed : ""} onChange={(event) => setObserved(event.target.value === "" ? NaN : Number(event.target.value))} /></label><label>Outcome and evidence note<textarea rows={3} value={outcomeNote} onChange={(event) => setOutcomeNote(event.target.value)} placeholder="Measurement window, source, confounders and what changed…" /></label><button type="button" onClick={() => { try { const feedback = recordFeedback(run, observed, outcomeNote); setState({ ...state, feedback: [feedback, ...state.feedback.filter((item) => item.runId !== run.id)] }); log("Outcome linked to the run. No model weights or production policy changed."); } catch (error) { log(error instanceof Error ? error.message : "Invalid feedback"); } }}>Record outcome</button></> : <button type="button" onClick={() => onSection("missions")}>Run a mission first</button>}<table className="os-table"><thead><tr><th>Run</th><th>Predicted</th><th>Observed</th></tr></thead><tbody>{state.feedback.map((item) => <tr key={item.id}><td>{item.runId}</td><td>{numberLabel(item.predictedService)}%</td><td>{numberLabel(item.observedService)}%</td></tr>)}</tbody></table></section>
      <section className="os-panel"><header><h2>Skill lifecycle</h2><small>{state.champion}</small></header><div className="os-metrics"><div><small>Distinct evaluated runs</small><strong>{skill.examples}</strong></div><div><small>Mean absolute service error</small><strong>{skill.mae === null ? "—" : `${numberLabel(skill.mae)} pp`}</strong></div></div><p>{skill.reason}</p><button type="button" disabled={!skill.shadowEligible} onClick={() => { setState({ ...state, champion: "continuity-review@1.1-shadow" }); log("Local challenger drafted for shadow evaluation. Production champion unchanged; no reinforcement-learning update ran."); }}>Draft shadow skill</button><button type="button" disabled={state.champion === "continuity-review@1.0"} onClick={() => { setState({ ...state, champion: "continuity-review@1.0" }); log("Shadow draft rolled back to the baseline skill reference."); }}>Roll back draft</button><h3>Before production learning</h3><ol><li>Log state, action, behavior policy, outcome and delayed reward.</li><li>Evaluate held-out history, action coverage and safe baseline fallback.</li><li>Compare in shadow without operational authority.</li><li>Require signed expert approval for a bounded pilot.</li></ol><p className="os-help">Three local outcomes only exercise the interface gate. They cannot establish predictive validity or justify real policy promotion. No live reinforcement learning is implemented.</p></section></div>}
    <details className="os-panel os-audit"><summary>Local activity ledger · {state.activity.length} entries</summary>{state.activity.map((entry, index) => <p key={`${entry}-${index}`}>{entry}</p>)}</details>
  </>;
}
