import type { ApplicationDetailId } from "./application-catalog";
import type { StatusTone } from "./platform-model";

export type ApplicationChange = {
  id: string;
  horizon: "Now" | "24 hours" | "7 days" | "30 days" | "90 days";
  asOf: string;
  title: string;
  entity: string;
  metric: string;
  previous: string;
  current: string;
  forecast: string;
  delta: string;
  cause: string;
  evidence: string;
  confidence: number;
  decisionTrigger: string;
  owner: string;
  downstream: string;
  tone: StatusTone;
};

export type LearningContract = {
  lastValidation: string;
  nextReview: string;
  driftTrigger: string;
  outcomeWindow: string;
  feedbackDestination: string;
  champion: string;
  challenger: string;
};

const changes: Record<ApplicationDetailId, readonly ApplicationChange[]> = {
  risk: [
    { id: "RR-C01", horizon: "Now", asOf: "04 Sep · 14:42 IST", title: "Graphite interruption probability crossed the action threshold", entity: "NeoGraph Materials → Graphite G-142", metric: "P(disruption within 30d)", previous: "48%", current: "72%", forecast: "82% no-action", delta: "+24 pts", cause: "A carrier booking withdrawal corroborated the capacity filing; source dependence was discounted.", evidence: "Synthetic filing + carrier milestone + supplier statement", confidence: 91, decisionTrigger: "Open continuity case when posterior probability exceeds 65% and time cover is below 21 days.", owner: "Continuity lead", downstream: "Network Optimizer scenario S-02", tone: "critical" },
    { id: "RR-C02", horizon: "24 hours", asOf: "04 Sep · 12:18 IST", title: "Red Sea recovery time widened", entity: "Singapore → Rotterdam corridor", metric: "P90 recovery duration", previous: "16 days", current: "21 days", forecast: "27 days compound", delta: "+5 days", cause: "Port dwell and convoy timing became positively correlated in the stress model.", evidence: "Synthetic terminal dwell + route regime model", confidence: 84, decisionTrigger: "Review Cape reroute when P90 recovery exceeds safety-stock cover.", owner: "Ocean risk owner", downstream: "Transport and inventory recourse", tone: "watch" },
    { id: "RR-C03", horizon: "7 days", asOf: "03 Sep · 18:06 IST", title: "Alternative supplier control strength improved", entity: "VietCarbon Advanced", metric: "Control effectiveness", previous: "41/100", current: "63/100", forecast: "78/100 after audit", delta: "+22", cause: "Capability evidence and reserved pilot capacity were approved in the synthetic qualification graph.", evidence: "Synthetic audit pack + reservation evidence", confidence: 88, decisionTrigger: "Reduce residual risk after two independent qualification gates pass.", owner: "Supplier recovery lead", downstream: "SupplierGraph qualification plan", tone: "opportunity" },
    { id: "RR-C04", horizon: "30 days", asOf: "02 Sep · 09:35 IST", title: "Customer concentration increased tail exposure", entity: "AX-4 North America", metric: "P95 margin loss", previous: "$3.6M", current: "$5.1M", forecast: "$6.4M no-action", delta: "+$1.5M", cause: "Three priority orders moved into the same constrained delivery window.", evidence: "Synthetic order promise + margin graph", confidence: 93, decisionTrigger: "Escalate when one dependency threatens more than $5M P95 margin.", owner: "Customer risk manager", downstream: "Decision case CASE-1024", tone: "critical" },
    { id: "RR-C05", horizon: "90 days", asOf: "30 Aug · 16:20 IST", title: "Model calibration improved after outcome replay", entity: "Maritime disruption event class", metric: "P90 empirical coverage", previous: "83.1%", current: "89.4%", forecast: "88–92% target band", delta: "+6.3 pts", cause: "Correlated-source signals were deduplicated and duration priors were recalibrated.", evidence: "Synthetic 24-event backtest", confidence: 96, decisionTrigger: "Promote challenger when coverage stays in band for two review cycles.", owner: "Model risk", downstream: "Risk model registry", tone: "healthy" },
    { id: "RR-C06", horizon: "24 hours", asOf: "04 Sep · 08:05 IST", title: "Documentation risk fell below materiality", entity: "Singapore transfer TX-044", metric: "Hold probability", previous: "38%", current: "14%", forecast: "8% after release", delta: "−24 pts", cause: "The unit-of-measure conflict was reconciled by the data steward.", evidence: "Synthetic customs document lineage", confidence: 97, decisionTrigger: "Close watch when probability is below 15% and evidence is complete.", owner: "Customs risk analyst", downstream: "FlowLens invoice release", tone: "healthy" },
  ],
  optimizer: [
    { id: "NO-C01", horizon: "Now", asOf: "04 Sep · 15:00 IST", title: "Service-first posture changes the response-space estimate", entity: "Graphite continuity calculation", metric: "Candidate-space index", previous: "412", current: "638", forecast: "701 after capacity confirmation", delta: "+226", cause: "Additional response authority and protected capacity expand the generated response-space indicator.", evidence: "Deterministic synthetic response fixture", confidence: 100, decisionTrigger: "Route only calculated responses with all 11 hard-family checks clear.", owner: "Network planner", downstream: "Human validation gate", tone: "opportunity" },
    { id: "NO-C02", horizon: "24 hours", asOf: "04 Sep · 13:10 IST", title: "Carbon envelope became binding", entity: "Emergency air allocation", metric: "Carbon slack", previous: "+1.8 pts", current: "0.0 pts", forecast: "−2.4 pts no-action", delta: "−1.8 pts", cause: "A second priority shipment was proposed for air transport.", evidence: "Synthetic route emissions + allocation candidate", confidence: 94, decisionTrigger: "Block release when modeled carbon delta exceeds the approved envelope.", owner: "Sustainability controller", downstream: "M-24 Pareto review", tone: "watch" },
    { id: "NO-C03", horizon: "7 days", asOf: "03 Sep · 17:42 IST", title: "Robustness budget lowered worst-case service loss", entity: "M-22 uncertainty set", metric: "Worst-case OTIF", previous: "88.7%", current: "93.4%", forecast: "94.1% with pilot capacity", delta: "+4.7 pts", cause: "Capacity and lead-time deviations were protected jointly instead of independently.", evidence: "Synthetic budgeted-uncertainty stress", confidence: 90, decisionTrigger: "Retain robust plan if price of robustness remains below $0.8M.", owner: "OR modeler", downstream: "Scenario comparison", tone: "healthy" },
    { id: "NO-C04", horizon: "30 days", asOf: "02 Sep · 11:30 IST", title: "Frozen bookings reduced plan churn", entity: "48-hour transport freeze zone", metric: "Committed moves changed", previous: "19", current: "4", forecast: "≤5 target", delta: "−15", cause: "M-26 rolling-horizon control fixed near-term confirmed moves.", evidence: "Synthetic current-vs-prior plan diff", confidence: 100, decisionTrigger: "Require executive override above five frozen changes.", owner: "Control-tower lead", downstream: "Action Room execution package", tone: "healthy" },
    { id: "NO-C05", horizon: "90 days", asOf: "30 Aug · 10:15 IST", title: "Greedy fallback regret narrowed", entity: "M-09 rapid response policy", metric: "Median objective regret", previous: "11.8%", current: "5.9%", forecast: "<5% target", delta: "−5.9 pts", cause: "Criticality-first ordering and a capacity-repair pass replaced cheapest-arc-only dispatch.", evidence: "Synthetic 40-case solved-history benchmark", confidence: 92, decisionTrigger: "Keep fallback only while median regret stays below 7%.", owner: "Planning COE", downstream: "Fallback policy registry", tone: "opportunity" },
    { id: "NO-C06", horizon: "7 days", asOf: "01 Sep · 14:55 IST", title: "Scenario reduction preserved tail behavior", entity: "M-20 stochastic scenario tree", metric: "Scenario count / CVaR change", previous: "64 / baseline", current: "12 / +0.7%", forecast: "12 retained", delta: "−52 scenarios", cause: "Low-impact duplicates were removed while preserving compound and recovery paths.", evidence: "Synthetic probability + tail-distance audit", confidence: 95, decisionTrigger: "Reject reduction if CVaR shifts more than 2%.", owner: "Model risk", downstream: "Replay performance", tone: "healthy" },
  ],
  flow: [
    { id: "FL-C01", horizon: "Now", asOf: "04 Sep · 14:51 IST", title: "Documentation release moved cash forward", entity: "Singapore transfer → invoice group 184", metric: "Expected cash date", previous: "19 Sep", current: "12 Sep", forecast: "10 Sep after proof of delivery", delta: "−7 days", cause: "The customs hold cleared and shipment-to-invoice linkage reached full confidence.", evidence: "Synthetic transfer + invoice reconciliation", confidence: 96, decisionTrigger: "Release billing when physical proof and customer terms reconcile.", owner: "Order-to-cash lead", downstream: "Receivables work queue", tone: "opportunity" },
    { id: "FL-C02", horizon: "24 hours", asOf: "04 Sep · 11:25 IST", title: "Emergency freight raised landed margin leakage", entity: "Controller A7 · Europe", metric: "Margin leakage", previous: "$0.8M", current: "$1.3M", forecast: "$1.6M no-action", delta: "+$0.5M", cause: "Two lots moved from protected ocean capacity to air.", evidence: "Synthetic TMS tariff + order margin", confidence: 93, decisionTrigger: "Re-optimize when expedite cost exceeds preserved contribution.", owner: "Supply-chain finance", downstream: "Network Optimizer carbon/cost frontier", tone: "watch" },
    { id: "FL-C03", horizon: "7 days", asOf: "03 Sep · 16:40 IST", title: "Inventory aging exposed avoidable working capital", entity: "AX-4 housings · Monterrey", metric: "Inventory >90 days", previous: "$11.2M", current: "$14.6M", forecast: "$9.8M after rebalance", delta: "+$3.4M", cause: "Launch timing moved while production lots remained unchanged.", evidence: "Synthetic ERP stock + demand version", confidence: 99, decisionTrigger: "Open rebalance action when aged value exceeds $12M.", owner: "Inventory finance", downstream: "Cash release queue", tone: "critical" },
    { id: "FL-C04", horizon: "30 days", asOf: "01 Sep · 09:10 IST", title: "Supplier milestone terms released near-term cash", entity: "Graphite contract G-142", metric: "13-week cash", previous: "$151M", current: "$158M", forecast: "$161M approved", delta: "+$7M", cause: "Payment moved from booking to receipt plus quality acceptance.", evidence: "Synthetic contract + AP schedule", confidence: 97, decisionTrigger: "Measure realized benefit after accepted receipt.", owner: "Procurement finance", downstream: "Supplier negotiation tracker", tone: "opportunity" },
    { id: "FL-C05", horizon: "90 days", asOf: "29 Aug · 12:00 IST", title: "Forecast-to-cash bias narrowed", entity: "13-week cash model", metric: "Absolute forecast bias", previous: "7.4%", current: "3.8%", forecast: "≤4% target", delta: "−3.6 pts", cause: "Transit and invoice delays were modeled jointly by customer term.", evidence: "Synthetic rolling-origin cash backtest", confidence: 94, decisionTrigger: "Recalibrate if bias exceeds 6% for two weeks.", owner: "Cash analytics", downstream: "Finance model registry", tone: "healthy" },
    { id: "FL-C06", horizon: "24 hours", asOf: "04 Sep · 07:30 IST", title: "Unmatched receipt exception increased", entity: "Pune receipt batch 2204", metric: "Unreconciled value", previous: "$0.4M", current: "$1.1M", forecast: "$0.2M after match", delta: "+$0.7M", cause: "A carrier reference changed without the invoice key.", evidence: "Synthetic ERP + carrier schema exception", confidence: 98, decisionTrigger: "Quarantine financial recognition until the source link is restored.", owner: "Financial controls", downstream: "Data Agent Hub remediation", tone: "critical" },
  ],
  demand: [
    { id: "DS-C01", horizon: "Now", asOf: "04 Sep · 14:34 IST", title: "North America AX-4 demand moved above supply", entity: "AX-4 · North America", metric: "90-day consensus", previous: "172K", current: "184K", forecast: "201K P90", delta: "+12K", cause: "Confirmed customer orders and incentive extension outweighed channel inventory.", evidence: "Synthetic orders + causal drivers", confidence: 92, decisionTrigger: "Send gap to Optimizer when P50 exceeds feasible supply by 5%.", owner: "Demand planning", downstream: "Allocation pattern", tone: "critical" },
    { id: "DS-C02", horizon: "24 hours", asOf: "04 Sep · 10:20 IST", title: "Launch-delay probability increased", entity: "NovaDrive program", metric: "P(delay >4 weeks)", previous: "21%", current: "37%", forecast: "44% downside", delta: "+16 pts", cause: "Customer engineering milestone moved and supplier release remains unconfirmed.", evidence: "Synthetic CRM milestone + supplier signal", confidence: 81, decisionTrigger: "Create downside scenario above 35% probability.", owner: "Commercial planning", downstream: "Production lot-sizing scenario", tone: "watch" },
    { id: "DS-C03", horizon: "7 days", asOf: "03 Sep · 13:15 IST", title: "Planner override reduced regional bias", entity: "Controller A7 · Europe", metric: "Rolling 8-week bias", previous: "+9.2%", current: "+3.1%", forecast: "+2.6%", delta: "−6.1 pts", cause: "The commercial pipeline was adjusted for duplicated opportunity stages.", evidence: "Synthetic override ledger + rolling backtest", confidence: 95, decisionTrigger: "Expire override after two unbiased forecast cycles.", owner: "Regional demand lead", downstream: "Consensus version DS-42.8", tone: "healthy" },
    { id: "DS-C04", horizon: "30 days", asOf: "01 Sep · 08:45 IST", title: "Intermittent spares demand widened uncertainty", entity: "Service spares · APAC", metric: "P90/P50 ratio", previous: "1.28×", current: "1.61×", forecast: "1.54×", delta: "+0.33×", cause: "Two rare repair events changed occurrence and size estimates.", evidence: "Synthetic M-03 occurrence-size model", confidence: 76, decisionTrigger: "Use service-cost simulation when ratio exceeds 1.5×.", owner: "Service-parts planner", downstream: "Inventory policy M-13", tone: "watch" },
    { id: "DS-C05", horizon: "90 days", asOf: "28 Aug · 17:00 IST", title: "Probabilistic coverage returned to target", entity: "Global demand ensemble", metric: "P10–P90 coverage", previous: "74%", current: "81%", forecast: "80% design target", delta: "+7 pts", cause: "Regime features and hierarchy reconciliation were added to the ensemble.", evidence: "Synthetic rolling-origin evaluation", confidence: 97, decisionTrigger: "Promote challenger after three target cycles.", owner: "Forecast science", downstream: "Demand model registry", tone: "healthy" },
    { id: "DS-C06", horizon: "7 days", asOf: "02 Sep · 15:40 IST", title: "Promotion uplift created a capacity opportunity", entity: "Energy storage · India", metric: "Unconstrained upside", previous: "$9.6M", current: "$18.4M", forecast: "$14.2M feasible", delta: "+$8.8M", cause: "A distributor promotion was approved while local plant utilization remained below 80%.", evidence: "Synthetic promotion + capacity snapshot", confidence: 89, decisionTrigger: "Open opportunity case when feasible margin exceeds $10M.", owner: "IBP lead", downstream: "Network Optimizer", tone: "opportunity" },
  ],
  suppliers: [
    { id: "SG-C01", horizon: "Now", asOf: "04 Sep · 14:12 IST", title: "Tier-2 ownership link changed risk propagation", entity: "NeoGraph Materials", metric: "Dependent revenue", previous: "$28M", current: "$42M", forecast: "$34M after alternate", delta: "+$14M", cause: "A previously separate mining entity resolved to the same parent group.", evidence: "Synthetic corporate filing + entity resolution", confidence: 94, decisionTrigger: "Recalculate concentration when ownership confidence exceeds 90%.", owner: "Supplier intelligence", downstream: "RiskRadar dependency score", tone: "critical" },
    { id: "SG-C02", horizon: "24 hours", asOf: "04 Sep · 09:05 IST", title: "VietCarbon capability match improved", entity: "VietCarbon Advanced", metric: "Qualification match", previous: "78%", current: "92%", forecast: "96% after pilot", delta: "+14 pts", cause: "Equipment, grade, and certification evidence were mapped to the product requirement.", evidence: "Synthetic audit + PLM capability graph", confidence: 91, decisionTrigger: "Shortlist above 85% with no compliance blocker.", owner: "Category sourcing", downstream: "Qualification workplan", tone: "opportunity" },
    { id: "SG-C03", horizon: "7 days", asOf: "03 Sep · 12:40 IST", title: "Primary supplier capacity headroom contracted", entity: "CellCore Industries", metric: "Available monthly capacity", previous: "18.2K", current: "11.6K", forecast: "9.4K downside", delta: "−6.6K", cause: "Shared-line demand from another product family moved into the same campaign.", evidence: "Synthetic supplier commitment + demand match", confidence: 87, decisionTrigger: "Reserve capacity when headroom falls below two weeks of demand.", owner: "Supplier manager", downstream: "M-06 sourcing allocation", tone: "watch" },
    { id: "SG-C04", horizon: "30 days", asOf: "31 Aug · 16:10 IST", title: "Certification expiry entered the planning horizon", entity: "IndoMat Energy · Site 03", metric: "Days to certificate expiry", previous: "142", current: "88", forecast: "58 at next review", delta: "−54 days", cause: "The renewal milestone has no approved auditor date.", evidence: "Synthetic QMS certificate record", confidence: 100, decisionTrigger: "Block new award inside a 60-day unmitigated window.", owner: "Supplier quality", downstream: "Qualification matrix", tone: "watch" },
    { id: "SG-C05", horizon: "90 days", asOf: "28 Aug · 11:35 IST", title: "Supplier score stability improved", entity: "Critical materials portfolio", metric: "30-day ranking churn", previous: "18%", current: "7%", forecast: "<8% target", delta: "−11 pts", cause: "Missing capacity was separated from true zero and evidence decay was added.", evidence: "Synthetic MCDA rank sensitivity", confidence: 96, decisionTrigger: "Review criteria if ranking churn exceeds 12%.", owner: "Supplier analytics", downstream: "M-25 qualification ranking", tone: "healthy" },
    { id: "SG-C06", horizon: "7 days", asOf: "02 Sep · 10:55 IST", title: "Single-source count fell after approved alternative", entity: "Precision castings", metric: "Single-source paths", previous: "46", current: "41", forecast: "35 after pilots", delta: "−5", cause: "Three sites and two part families received conditional approval.", evidence: "Synthetic QMS approval graph", confidence: 98, decisionTrigger: "Count only effective, site-specific, capacity-backed approvals.", owner: "Resilience sourcing", downstream: "Enterprise dependency KPI", tone: "opportunity" },
  ],
  agents: [
    { id: "DA-C01", horizon: "Now", asOf: "04 Sep · 14:58 IST", title: "Carrier schema drift quarantined 1,842 records", entity: "Logistics Movement Agent", metric: "Quality quarantine", previous: "18", current: "1,842", forecast: "0 after replay", delta: "+1,824", cause: "The carrier changed ETA timezone and container-weight field names.", evidence: "Synthetic schema contract v18 → v19", confidence: 100, decisionTrigger: "Pause graph merge when required fields violate the versioned contract.", owner: "Data product owner", downstream: "Mapping remediation queue", tone: "critical" },
    { id: "DA-C02", horizon: "24 hours", asOf: "04 Sep · 12:05 IST", title: "Agent pause protected downstream decisions", entity: "External Intelligence Agent", metric: "Records withheld", previous: "0", current: "12,418", forecast: "12,418 pending review", delta: "+12,418", cause: "Source license scope did not match the approved regional policy.", evidence: "Synthetic policy decision log", confidence: 100, decisionTrigger: "Fail closed when policy scope cannot be proven.", owner: "Data governance", downstream: "RiskRadar source coverage", tone: "watch" },
    { id: "DA-C03", horizon: "7 days", asOf: "03 Sep · 15:30 IST", title: "Entity-resolution throughput increased", entity: "Supplier Discovery Agent", metric: "Resolved entities / hour", previous: "42K", current: "68K", forecast: "72K stable", delta: "+26K", cause: "Candidate blocking keys reduced unnecessary pair comparisons.", evidence: "Synthetic agent run history", confidence: 99, decisionTrigger: "Promote worker version after SLO and match-quality gates pass.", owner: "Graph platform", downstream: "SupplierGraph coverage", tone: "opportunity" },
    { id: "DA-C04", horizon: "30 days", asOf: "01 Sep · 14:00 IST", title: "Data freshness SLO burn increased", entity: "ERP Observation Agent", metric: "Monthly SLO budget consumed", previous: "31%", current: "68%", forecast: "83% no action", delta: "+37 pts", cause: "Three source maintenance windows delayed order and inventory deltas.", evidence: "Synthetic run telemetry + source calendar", confidence: 100, decisionTrigger: "Escalate above 75% burn before month end.", owner: "Platform reliability", downstream: "Data freshness control", tone: "watch" },
    { id: "DA-C05", horizon: "90 days", asOf: "29 Aug · 09:20 IST", title: "Policy-denied field access fell", entity: "All observation agents", metric: "Denied field requests / 1M", previous: "14.2", current: "3.8", forecast: "<4 target", delta: "−10.4", cause: "Connector manifests were aligned to minimum approved field sets.", evidence: "Synthetic access-control audit", confidence: 100, decisionTrigger: "Block release on any unapproved restricted field.", owner: "Security architecture", downstream: "Connector certification", tone: "healthy" },
    { id: "DA-C06", horizon: "24 hours", asOf: "04 Sep · 08:50 IST", title: "Graph merge latency recovered", entity: "Knowledge Graph Merge Agent", metric: "P95 merge latency", previous: "18.4 min", current: "6.7 min", forecast: "<8 min SLO", delta: "−11.7 min", cause: "High-degree entity updates were isolated into bounded batches.", evidence: "Synthetic processing trace", confidence: 99, decisionTrigger: "Return to normal cadence after three healthy windows.", owner: "Graph operations", downstream: "All application freshness", tone: "healthy" },
  ],
  graph: [
    { id: "KG-C01", horizon: "Now", asOf: "04 Sep · 14:54 IST", title: "Entity merge changed the critical dependency path", entity: "NeoGraph parent group", metric: "Graph degree", previous: "28 links", current: "42 links", forecast: "45 after steward review", delta: "+14", cause: "Three legal entities resolved to one parent with shared capacity and ownership.", evidence: "Synthetic filing + ERP supplier identity", confidence: 94, decisionTrigger: "Repropagate risk when a merge changes material dependency above 5%.", owner: "Knowledge steward", downstream: "RiskRadar path recalculation", tone: "critical" },
    { id: "KG-C02", horizon: "24 hours", asOf: "04 Sep · 11:40 IST", title: "Conflicting unit assertions lowered confidence", entity: "Graphite G-142 capacity", metric: "Assertion confidence", previous: "96%", current: "74%", forecast: "98% after steward decision", delta: "−22 pts", cause: "Supplier statement used tonnes/month while ERP mapping interpreted kilograms/week.", evidence: "Synthetic source disagreement record", confidence: 100, decisionTrigger: "Quarantine derived capacity below 80% confidence.", owner: "Material data steward", downstream: "Optimizer capacity input", tone: "critical" },
    { id: "KG-C03", horizon: "7 days", asOf: "03 Sep · 10:25 IST", title: "Evidence decay moved a relationship to review", entity: "Kansai Graphite supplies CellCore", metric: "Relationship confidence", previous: "91%", current: "79%", forecast: "65% without refresh", delta: "−12 pts", cause: "The last site-specific declaration exceeded its approved evidence age.", evidence: "Synthetic temporal assertion policy", confidence: 100, decisionTrigger: "Request refresh below 80%; exclude below 70%.", owner: "Supplier graph steward", downstream: "Alternative shortlist", tone: "watch" },
    { id: "KG-C04", horizon: "30 days", asOf: "01 Sep · 07:45 IST", title: "Order-to-margin coverage improved", entity: "Open customer-order subgraph", metric: "Evidence-backed margin links", previous: "78%", current: "91%", forecast: "94% after close", delta: "+13 pts", cause: "Invoice and product-margin keys were reconciled across business units.", evidence: "Synthetic finance graph merge", confidence: 97, decisionTrigger: "Allow portfolio optimization above 90% coverage.", owner: "Finance data product", downstream: "FlowLens and portfolio model", tone: "opportunity" },
    { id: "KG-C05", horizon: "90 days", asOf: "28 Aug · 12:30 IST", title: "Ontology coverage expanded to transfer custody", entity: "Movement and custody ontology", metric: "Mapped relationship types", previous: "64", current: "78", forecast: "84 next release", delta: "+14", cause: "Inbound asset, custodian, customs, and outbound asset relationships were added.", evidence: "Synthetic ontology release KG-3.8", confidence: 100, decisionTrigger: "Version all application queries when semantics change.", owner: "Ontology council", downstream: "Network Radar transfer layer", tone: "healthy" },
    { id: "KG-C06", horizon: "7 days", asOf: "02 Sep · 16:05 IST", title: "Mapping exception backlog fell", entity: "Business review queue", metric: "Critical exceptions", previous: "21", current: "12", forecast: "7 by next review", delta: "−9", cause: "High-value material and order conflicts were prioritized by decision impact.", evidence: "Synthetic steward action log", confidence: 100, decisionTrigger: "Escalate any unresolved exception blocking a decision due in 24 hours.", owner: "Data governance lead", downstream: "Decision Inbox", tone: "opportunity" },
  ],
};

export const learningContracts: Record<ApplicationDetailId, LearningContract> = {
  risk: { lastValidation: "Synthetic replay dated 30 Aug 2026 · 24-event outcome fixture", nextReview: "Illustrative target · 13 Sep 2026", driftTrigger: "P90 coverage outside 88–92% or signal mix shift >15%", outcomeWindow: "30 / 90 / 180 days after control", feedbackDestination: "Event priors, recovery distributions, and control-effectiveness registry", champion: "Bayesian graph risk v3.6", challenger: "Regime-aware risk v3.7-rc" },
  optimizer: { lastValidation: "Synthetic replay dated 03 Sep 2026 · 40-case estimate fixture", nextReview: "Illustrative target · 10 Sep 2026", driftTrigger: "Hard-check escape, regret >5%, or decision-contract fingerprint mismatch", outcomeWindow: "At review, execution, and 30-day realized outcome", feedbackDestination: "Formulation, parameter, scenario, and fallback-policy registry", champion: "Continuity calculator OR-2.5", challenger: "Distributionally robust design OR-2.6-rc" },
  flow: { lastValidation: "Synthetic replay dated 01 Sep 2026 · month-close fixture", nextReview: "Illustrative target · 08 Sep 2026", driftTrigger: "Cash bias >6% or physical-financial match below 98%", outcomeWindow: "Weekly realization + accounting close", feedbackDestination: "Cash timing, recognition, and action-realization models", champion: "Cash bridge 18.7", challenger: "Customer-term survival 18.8-rc" },
  demand: { lastValidation: "Synthetic replay dated 02 Sep 2026 · rolling-origin cycle 42", nextReview: "Illustrative target · 09 Sep 2026", driftTrigger: "WAPE +3 pts, bias >5%, or interval coverage outside 76–84%", outcomeWindow: "Weekly forecast vintages through 13 weeks", feedbackDestination: "Feature, override, hierarchy, and scenario library", champion: "Global ensemble DS-42.8", challenger: "Regime ensemble DS-43-rc" },
  suppliers: { lastValidation: "Synthetic replay dated 31 Aug 2026 · rank-and-match fixture", nextReview: "Illustrative target · 14 Sep 2026", driftTrigger: "Ranking churn >12% or evidence-backed link coverage <90%", outcomeWindow: "Qualification milestone + 90-day supplier performance", feedbackDestination: "Capability ontology, MCDA weights, and evidence decay", champion: "Supplier match SG-9.4", challenger: "Capacity-aware match SG-9.5-rc" },
  agents: { lastValidation: "Synthetic replay dated 04 Sep 2026 · connector-contract fixture", nextReview: "Illustrative target · 05 Sep 2026", driftTrigger: "SLO budget >75%, schema incompatibility, or policy-denied field", outcomeWindow: "Every run + daily SLO review", feedbackDestination: "Connector contract, mapping rules, and policy manifests", champion: "Agent fabric DA-6.2", challenger: "Bounded merge DA-6.3-rc" },
  graph: { lastValidation: "Synthetic replay dated 03 Sep 2026 · reconciliation fixture", nextReview: "Illustrative target · 10 Sep 2026", driftTrigger: "Critical disagreement, ontology change, or confidence decay below threshold", outcomeWindow: "Every merge + decision outcome linkage", feedbackDestination: "Entity resolution, ontology, source reliability, and temporal assertions", champion: "Knowledge graph KG-3.8", challenger: "Temporal provenance KG-3.9-rc" },
};

export function getApplicationChanges(id: ApplicationDetailId) {
  return changes[id];
}
