"use client";

import { useState } from "react";
import { dataAgents, type AgentStatus, type DataViewId, type ScopeSnapshot, type StatusTone } from "./platform-model";

type DataOperationsProps = {
  view: DataViewId;
  snapshot: ScopeSnapshot;
  onOpenApp: (app: "risk" | "optimizer" | "flow" | "demand" | "suppliers") => void;
  onToast: (message: string) => void;
};

function Dot({ tone }: { tone: StatusTone }) {
  return <i className={`tone-dot tone-${tone}`} aria-hidden="true" />;
}

function AgentHub({ snapshot, onToast }: Pick<DataOperationsProps, "snapshot" | "onToast">) {
  const [statuses, setStatuses] = useState<Record<string, AgentStatus>>(() => Object.fromEntries(dataAgents.map((agent) => [agent.id, agent.status])));
  const [filter, setFilter] = useState("All agents");
  const [selectedAgent, setSelectedAgent] = useState(dataAgents[0]);
  const filteredAgents = dataAgents.filter((agent) => filter === "All agents" || statuses[agent.id] === filter.toLowerCase());
  const running = Object.values(statuses).filter((status) => status === "running").length;
  const toggleAgent = (id: string) => {
    setStatuses((current) => {
      const next = current[id] === "paused" ? "running" : "paused";
      onToast(`${dataAgents.find((agent) => agent.id === id)?.name} ${next === "running" ? "resumed" : "paused"} in concept mode.`);
      return { ...current, [id]: next };
    });
  };

  return (
    <div className="data-workspace agent-workspace">
      <section className="data-intro"><div className="app-code">DA</div><div><p className="kicker">CONNECTED DATA PLATFORM · {snapshot.shortLabel.toUpperCase()}</p><h1 tabIndex={-1} data-page-heading>Data Agent Hub</h1><p>Deploy policy-controlled agents inside the client environment to observe approved systems, documents, messages, portals, and events—then continuously resolve them into a private operational knowledge graph.</p></div><aside><span>OPERATING PRINCIPLE</span><b>Data stays governed. Meaning becomes connected.</b><button type="button" onClick={() => onToast("Agent deployment wizard opened in concept mode.")}>Deploy an agent →</button></aside></section>
      <div className="app-metrics"><article className="app-metric app-metric-healthy"><div><span>Agents running</span><Dot tone="healthy" /></div><strong>{running}/6</strong><p>Across client + platform boundaries</p></article><article className="app-metric"><div><span>Records observed</span><Dot tone="info" /></div><strong>111M</strong><p>Structured + unstructured evidence</p></article><article className="app-metric app-metric-opportunity"><div><span>Graph entities</span><Dot tone="opportunity" /></div><strong>8.4M</strong><p>27.6M resolved relationships</p></article><article className="app-metric app-metric-watch"><div><span>Quality exceptions</span><Dot tone="watch" /></div><strong>214</strong><p>12 require business review</p></article></div>

      <section className="ingestion-pipeline panel" aria-labelledby="pipeline-title"><header className="panel-header"><div><p className="kicker">INGESTION + KNOWLEDGE PIPELINE</p><h2 id="pipeline-title">From source evidence to controlled application context</h2><span>Every stage is observable, replayable, policy-scoped, and attributable.</span></div><span className="live-chip"><Dot tone="healthy" />18 sec end-to-end latency</span></header><div className="pipeline-stages">{[
        ["01","Observe","ERP · PLM · TMS · files · web","111M records","healthy"], ["02","Extract","Tables · documents · events · messages","99.1% parsed","healthy"], ["03","Resolve","Identity · unit · hierarchy · time","214 exceptions","watch"], ["04","Connect","Entities + evidence + relationships","27.6M links","opportunity"], ["05","Reason","Signals · impacts · scenarios · controls","5 decision apps","info"], ["06","Act","Approval · write-back · measurement","Human gated","healthy"],
      ].map((stage, index) => <article key={stage[0]}><span>{stage[0]}</span><Dot tone={stage[4] as StatusTone} /><b>{stage[1]}</b><p>{stage[2]}</p><strong>{stage[3]}</strong>{index < 5 && <i>→</i>}</article>)}</div><footer><span><b>PRIVATE RAW ZONE</b> Source records remain inside the client boundary</span><span><b>SHARED SIGNAL ZONE</b> Only governed, anonymized signals can cross tenants</span></footer></section>

      <section className="panel agent-register"><header className="panel-header"><div><p className="kicker">AGENT FLEET</p><h2>Observe every approved source without replacing it</h2></div><div className="segmented-control compact">{["All agents","Running","Attention","Paused"].map((item) => <button className={filter === item ? "active" : ""} type="button" key={item} onClick={() => setFilter(item)}>{item}</button>)}</div></header><div className="agent-list">{filteredAgents.map((agent) => { const status = statuses[agent.id]; const tone: StatusTone = status === "running" ? "healthy" : status === "attention" ? "watch" : "info"; return <article className={selectedAgent.id === agent.id ? "selected" : ""} key={agent.id}><button className="agent-main" type="button" onClick={() => setSelectedAgent(agent)}><span className={`agent-icon agent-icon-${status}`}>{agent.name.split(" ").map((word) => word[0]).join("").slice(0,2)}</span><div><b>{agent.name}</b><small>{agent.source}</small></div><span className={`state-chip state-${tone}`}><Dot tone={tone} />{status}</span></button><div className="agent-stat"><small>FRESHNESS</small><b>{status === "paused" ? "Paused" : agent.freshness}</b></div><div className="agent-stat"><small>RECORDS</small><b>{agent.records}</b></div><div className="agent-stat"><small>QUALITY</small><b>{agent.quality}%</b></div><div className="agent-stat"><small>BOUNDARY</small><b>{agent.boundary}</b></div><button className="agent-control" type="button" onClick={() => toggleAgent(agent.id)}>{status === "paused" ? "Resume" : "Pause"}</button></article>})}</div></section>

      <div className="data-grid">
        <section className="panel agent-detail"><header className="panel-header"><div><p className="kicker">SELECTED AGENT</p><h2>{selectedAgent.name}</h2></div><span className="model-status">POLICY SIGNED</span></header><div className="agent-detail-hero"><span>{selectedAgent.source}</span><b>{selectedAgent.mode}</b><p>{selectedAgent.entities}</p></div><dl><div><dt>Execution boundary</dt><dd>{selectedAgent.boundary}</dd></div><div><dt>Credential mode</dt><dd>Customer-managed identity</dd></div><div><dt>Write access</dt><dd>Off · approval required</dd></div><div><dt>Raw retention</dt><dd>Customer policy</dd></div><div><dt>Cross-tenant training</dt><dd>Disabled</dd></div><div><dt>Evidence lineage</dt><dd>100% retained</dd></div></dl><div className="agent-actions"><button type="button">Inspect policy</button><button type="button">View recent runs</button><button className="primary-action" type="button" onClick={() => onToast(`${selectedAgent.name} test run started.`)}>Run test ingestion →</button></div></section>
        <section className="panel ingestion-events"><header className="panel-header"><div><p className="kicker">LIVE INGESTION EVENTS</p><h2>What the system is learning now</h2></div><span className="live-chip"><Dot tone="healthy" />Streaming</span></header><ol>{[
          ["11:42:18","ERP transaction agent","1,284 order changes merged","healthy"], ["11:42:04","Movement agent","MV Meridian Star ETA revised +3.4d","watch"], ["11:41:52","Market intelligence swarm","Capacity agreement evidence corroborated","critical"], ["11:41:31","Product knowledge agent","42 BOM revisions connected to AX-4","healthy"], ["11:41:08","Supplier portal agent","12 carbon evidence fields unresolved","watch"], ["11:40:44","Identity resolution","NeoGraph parent entity confirmed","opportunity"],
        ].map((event) => <li key={`${event[0]}-${event[2]}`}><time>{event[0]}</time><Dot tone={event[3] as StatusTone} /><div><b>{event[2]}</b><small>{event[1]}</small></div></li>)}</ol></section>
      </div>
    </div>
  );
}

function KnowledgeGraph({ snapshot, onOpenApp, onToast }: Omit<DataOperationsProps, "view">) {
  const graphNodes = [
    { id: "event", label: "Capacity agreement", kind: "External event", tone: "critical" as const, x: 8, y: 24, facts: "3 filings · 91% confidence" },
    { id: "company", label: "NeoGraph Materials", kind: "Company", tone: "watch" as const, x: 29, y: 18, facts: "Resolved identity · Tier 2" },
    { id: "material", label: "Graphite G-142", kind: "Material", tone: "critical" as const, x: 47, y: 42, facts: "92% dependency · $18.4M spend" },
    { id: "part", label: "Cell module C8", kind: "Component", tone: "watch" as const, x: 66, y: 18, facts: "4 BOM positions · 2 programs" },
    { id: "plant", label: "Pune Plant 02", kind: "Plant", tone: "healthy" as const, x: 65, y: 66, facts: "486 orders · 14 days cover" },
    { id: "product", label: "AX-4 drive unit", kind: "Product", tone: "watch" as const, x: 84, y: 44, facts: "$42M customer value" },
    { id: "order", label: "28 priority orders", kind: "Customer demand", tone: "critical" as const, x: 88, y: 75, facts: "$4.2M margin exposure" },
    { id: "supplier", label: "VietCarbon", kind: "Alternative", tone: "opportunity" as const, x: 29, y: 72, facts: "92% capability match" },
  ];
  const edges = [["event","company"],["company","material"],["supplier","material"],["material","part"],["material","plant"],["part","product"],["plant","product"],["product","order"]];
  const [selected, setSelected] = useState(graphNodes[2]);
  const [layer, setLayer] = useState("Business impact");
  const graphIndex = new Map(graphNodes.map((node) => [node.id,node]));

  return (
    <div className="data-workspace graph-workspace">
      <section className="data-intro"><div className="app-code">KG</div><div><p className="kicker">PRIVATE KNOWLEDGE PLATFORM · {snapshot.shortLabel.toUpperCase()}</p><h1 tabIndex={-1} data-page-heading>Operational Knowledge Graph</h1><p>Resolve fragmented records into a living model of companies, sites, materials, products, orders, movements, cash, events, evidence, decisions, and outcomes—without losing source lineage.</p></div><aside><span>GRAPH READINESS</span><b>8.4M entities · 27.6M relationships</b><button type="button" onClick={() => onToast("Graph export prepared with synthetic references only.")}>Export governed subgraph →</button></aside></section>
      <div className="app-metrics"><article className="app-metric"><div><span>Entities</span><Dot tone="info" /></div><strong>8.4M</strong><p>98.2% identity resolved</p></article><article className="app-metric app-metric-opportunity"><div><span>Relationships</span><Dot tone="opportunity" /></div><strong>27.6M</strong><p>96.8% evidence backed</p></article><article className="app-metric app-metric-healthy"><div><span>Source lineage</span><Dot tone="healthy" /></div><strong>100%</strong><p>Every fact traceable</p></article><article className="app-metric app-metric-watch"><div><span>Mapping exceptions</span><Dot tone="watch" /></div><strong>214</strong><p>12 business-critical</p></article></div>
      <section className="panel graph-toolbar"><div className="segmented-control wide">{["Business impact","Supply network","Money flow","Evidence lineage"].map((item) => <button className={layer === item ? "active" : ""} type="button" key={item} onClick={() => setLayer(item)}>{item}</button>)}</div><label>Entity type<select><option>All entities</option><option>Supplier</option><option>Material</option><option>Product</option><option>Order</option></select></label><label>Confidence<select><option>All confidence</option><option>Above 90%</option><option>Review required</option></select></label><button type="button">Fit graph ⛶</button></section>
      <section className="panel knowledge-canvas-panel"><header className="panel-header"><div><p className="kicker">{layer.toUpperCase()} LAYER</p><h2>Graphite capacity → customer and margin exposure</h2><span>Click any entity to inspect facts, sources, confidence, and application use.</span></div><div className="map-legend"><span><Dot tone="critical" />Critical</span><span><Dot tone="healthy" />Verified</span><span><Dot tone="opportunity" />Alternative</span></div></header><div className="knowledge-layout"><div className="knowledge-canvas">{edges.map(([fromId,toId],index) => { const from = graphIndex.get(fromId)!; const to=graphIndex.get(toId)!; const dx=to.x-from.x,dy=to.y-from.y,length=Math.sqrt(dx*dx+dy*dy),angle=Math.atan2(dy,dx)*180/Math.PI; return <i className="kg-edge" key={`${fromId}-${toId}`} style={{left:`${from.x}%`,top:`${from.y}%`,width:`${length}%`,transform:`rotate(${angle}deg)`}}><span>{index % 2 ? "SUPPLIES" : "LINKED TO"}</span></i>; })}{graphNodes.map((node) => <button className={`kg-node kg-node-${node.tone} ${selected.id === node.id ? "selected" : ""}`} type="button" key={node.id} style={{left:`${node.x}%`,top:`${node.y}%`}} onClick={() => setSelected(node)}><small>{node.kind}</small><b>{node.label}</b><span>{node.facts}</span></button>)}<div className="graph-provenance"><span><Dot tone="healthy" />Observed fact</span><span><Dot tone="info" />Resolved relationship</span><span><Dot tone="watch" />Inferred · reviewable</span></div></div><aside className="entity-inspector"><div className="entity-title"><span>{selected.kind.split(" ").map((word)=>word[0]).join("").slice(0,2)}</span><div><p className="kicker">SELECTED ENTITY</p><h3>{selected.label}</h3></div><Dot tone={selected.tone} /></div><p>{selected.facts}. This entity is connected to the selected {layer.toLowerCase()} path and retains all contributing evidence.</p><dl><div><dt>Entity type</dt><dd>{selected.kind}</dd></div><div><dt>Confidence</dt><dd>96.8%</dd></div><div><dt>Last changed</dt><dd>18 sec ago</dd></div><div><dt>Graph degree</dt><dd>42 links</dd></div></dl><div className="source-proof"><p className="kicker">SOURCE EVIDENCE</p>{[["SAP S/4HANA","Observed","healthy"],["Teamcenter PLM","Observed","healthy"],["Public filing","Corroborated","info"],["Analyst mapping","Approved","opportunity"]].map((source) => <button type="button" key={source[0]}><Dot tone={source[2] as StatusTone} /><span><b>{source[0]}</b><small>{source[1]} · source ID retained</small></span><em>→</em></button>)}</div><p className="kicker app-use-kicker">USED BY APPLICATIONS</p><div className="entity-apps">{[["RiskRadar","risk"],["Optimizer","optimizer"],["FlowLens","flow"],["SupplierGraph","suppliers"]].map((app) => <button type="button" key={app[0]} onClick={() => onOpenApp(app[1] as "risk" | "optimizer" | "flow" | "suppliers")}><span>{app[0].slice(0,2).toUpperCase()}</span><b>{app[0]}</b><em>→</em></button>)}</div></aside></div></section>
      <div className="data-grid graph-bottom-grid"><section className="panel schema-coverage"><header className="panel-header"><div><p className="kicker">BUSINESS ONTOLOGY COVERAGE</p><h2>What the graph understands</h2></div></header>{[["Supplier + ownership",98,"6,420 entities"],["Material + component",94,"88,214 entities"],["Product + BOM",97,"4.6M relationships"],["Order + customer",99,"18,402 open orders"],["Movement + cargo",93,"2,164 active movements"],["Cost + margin",86,"3 families partial"],["Carbon + evidence",76,"12 suppliers incomplete"]].map((item) => <article key={item[0]}><div><b>{item[0]}</b><small>{item[2]}</small></div><div className="progress-track"><i className={Number(item[1]) < 85 ? "fill-watch" : "fill-healthy"} style={{width:`${item[1]}%`}} /></div><strong>{item[1]}%</strong></article>)}</section><section className="panel mapping-queue"><header className="panel-header"><div><p className="kicker">HUMAN REVIEW QUEUE</p><h2>Mappings that need business judgment</h2></div><span className="state-chip state-watch">12 critical</span></header>{[["MAP-214","Graphite G-142","Material ID conflicts with PLM grade","62%"],["MAP-209","NeoGraph Materials","Duplicate legal entity","81%"],["MAP-197","AX-4 housing","Unit conversion missing","74%"],["MAP-188","Chennai route 04","No current emissions factor","93%"]].map((item) => <button type="button" key={item[0]} onClick={() => onToast(`${item[0]} review opened.`)}><span>{item[0]}</span><div><b>{item[1]}</b><small>{item[2]}</small></div><strong>{item[3]}</strong><em>Review →</em></button>)}</section></div>
    </div>
  );
}

export default function DataOperations({ view, snapshot, onOpenApp, onToast }: DataOperationsProps) {
  if (view === "agents") return <AgentHub snapshot={snapshot} onToast={onToast} />;
  return <KnowledgeGraph snapshot={snapshot} onOpenApp={onOpenApp} onToast={onToast} />;
}
