export type ORMethodFamily = "Diagnose & forecast" | "Exact optimization" | "Fast search & decomposition" | "Inventory, flow & reliability" | "Simulation" | "Uncertainty & risk" | "Decision systems & governance";
export type MethodRole = "Primary" | "Supporting" | "Fallback" | "Experimental";

export type ORMethod = {
  code: `M-${string}`;
  name: string;
  family: ORMethodFamily;
  purpose: string;
  formulation: string;
  techniques: readonly string[];
  outputs: readonly string[];
  validation: readonly string[];
  limitations: string;
  runtime: string;
  decisionShapes: readonly string[];
};

export const orMethods: readonly ORMethod[] = [
  { code: "M-01", name: "Exploratory diagnostics and statistical process control", family: "Diagnose & forecast", purpose: "Find drift, bias, outliers, unstable processes, and unusable model inputs before optimization.", formulation: "Segment observations by item, location, supplier, and time; estimate stable limits and governed exception rules.", techniques: ["Distribution profiling", "Control charts", "Change-point detection", "Missingness and outlier diagnostics"], outputs: ["Fitness status", "Drift alert", "Control-limit breach", "Data repair queue"], validation: ["Known-event replay", "Stable-period false-alarm rate", "Reproducible feature profile"], limitations: "A signal is not automatically a causal explanation; changing regimes require re-baselining.", runtime: "Seconds to minutes", decisionShapes: ["Every model input", "Quality", "Monitoring"] },
  { code: "M-02", name: "Time-series, causal, and hierarchical forecasting", family: "Diagnose & forecast", purpose: "Create reconciled point and probabilistic forecasts at SKU, family, region, and network levels.", formulation: "Minimize forecast loss while enforcing hierarchy reconciliation, non-negativity, and approved causal drivers.", techniques: ["ETS / ARIMA", "Causal regression", "Gradient ensembles", "Hierarchical reconciliation", "Quantile forecasting"], outputs: ["P10 / P50 / P90 forecast", "Driver contribution", "Reconciled totals", "Forecast version"], validation: ["Rolling-origin backtest", "Bias / MASE / WAPE", "Pinball loss", "Interval coverage"], limitations: "Structural breaks and unavailable future drivers can dominate historical accuracy.", runtime: "Minutes to hours", decisionShapes: ["Demand", "Capacity", "Price", "Lead time"] },
  { code: "M-03", name: "Intermittent-demand forecasting", family: "Diagnose & forecast", purpose: "Estimate occurrence and size for sparse service parts and low-frequency materials.", formulation: "Model non-zero demand size separately from inter-arrival time, then feed service and reorder decisions.", techniques: ["Croston-style forecasting", "Syntetos–Boylan adjustment", "Zero-inflated models", "Occurrence-size decomposition"], outputs: ["Occurrence probability", "Conditional size", "Demand interval", "Buffer input"], validation: ["Backtest service and cost", "Compare with naive sparse baseline", "Calibration by intermittency class"], limitations: "Aggregate error metrics can hide costly stockout behavior for rare critical items.", runtime: "Seconds to minutes", decisionShapes: ["Spares", "Long-tail inventory", "Repair parts"] },
  { code: "M-04", name: "Bayesian inference and state estimation", family: "Diagnose & forecast", purpose: "Update latent demand, disruption, failure, and supplier-state beliefs as evidence arrives.", formulation: "Combine prior, likelihood, transition dynamics, and signal reliability into a posterior state.", techniques: ["Bayesian updating", "Hidden Markov models", "Kalman / particle filtering", "Posterior predictive checks"], outputs: ["Posterior probability", "Credible interval", "Evidence contribution", "Decision reversal threshold"], validation: ["Prior sensitivity", "Posterior calibration", "Posterior predictive replay"], limitations: "Weak priors or correlated evidence can create unjustified certainty.", runtime: "Seconds to minutes", decisionShapes: ["Risk sensing", "Asset condition", "Supplier recovery"] },
  { code: "M-05", name: "Linear programming and minimum-cost network flow", family: "Exact optimization", purpose: "Allocate divisible flow through a network at lowest landed cost or highest served value.", formulation: "Continuous node-lane-product-time flows with conservation, supply, demand, capacity, service, and eligibility constraints.", techniques: ["Simplex", "Interior point", "Shortest path", "Maximum flow", "Minimum-cost flow", "Matching"], outputs: ["Flow plan", "Chosen paths", "Dual values", "Reduced costs", "Binding arcs"], validation: ["Primal and dual feasibility", "Flow conservation", "Baseline improvement"], limitations: "Continuous relaxations cannot represent indivisible setups, lots, or yes/no choices without extension.", runtime: "Seconds to minutes", decisionShapes: ["Allocation", "Transport", "Order promising"] },
  { code: "M-06", name: "Mixed-integer linear programming", family: "Exact optimization", purpose: "Optimize networks with discrete facilities, suppliers, lanes, setups, assignments, and batches.", formulation: "Continuous flows plus binary/integer decisions under linear objective and constraints.", techniques: ["Branch-and-bound", "Branch-and-cut", "Cutting planes", "Presolve", "Warm starts"], outputs: ["Incumbent plan", "Best bound", "Certified gap", "Discrete choices", "Constraint residuals"], validation: ["Integrality and feasibility", "Bound / gap integrity", "Small-instance enumeration", "Replay fingerprint"], limitations: "Runtime can grow sharply with weak formulations, symmetry, or excessive scenarios.", runtime: "Seconds to hours", decisionShapes: ["Network design", "Sourcing", "Production", "Portfolio"] },
  { code: "M-07", name: "Dynamic programming and lot sizing", family: "Exact optimization", purpose: "Choose sequential order, inventory, maintenance, or replacement decisions over a finite horizon.", formulation: "State, action, transition, stage cost, and terminal value linked through Bellman recursion.", techniques: ["Wagner–Whitin lot sizing", "Shortest-path DP", "Backward induction", "State-space reduction"], outputs: ["Period policy", "Lot plan", "State value", "Replacement threshold"], validation: ["Bellman recursion check", "Terminal-state check", "Small-instance brute force"], limitations: "State and action dimensionality can cause a curse of dimensionality.", runtime: "Seconds to hours", decisionShapes: ["Lot sizing", "Inventory policy", "Maintenance"] },
  { code: "M-08", name: "Constraint programming and CP-SAT", family: "Exact optimization", purpose: "Build feasible schedules and assignments with rich logical, calendar, sequencing, and compatibility rules.", formulation: "Intervals, start/end times, assignment variables, precedence, non-overlap, skills, and calendars.", techniques: ["Constraint propagation", "SAT", "CP-SAT", "No-overlap and cumulative constraints", "Large-neighborhood search"], outputs: ["Gantt schedule", "Assignments", "Feasible / proven status", "Bound"], validation: ["No-overlap checks", "Precedence satisfaction", "Calendar and skill feasibility"], limitations: "Objective scaling and model-specific search settings materially affect performance.", runtime: "Seconds to hours", decisionShapes: ["Scheduling", "Dock doors", "Workforce", "Maintenance"] },
  { code: "M-09", name: "Greedy graph and dispatch algorithms", family: "Fast search & decomposition", purpose: "Return a transparent feasible response under strict latency or as a solver warm start/fallback.", formulation: "Apply a documented ordering key and incremental feasibility test, then repair remaining violations.", techniques: ["Shortest path", "Cheapest feasible arc", "Earliest due date", "Shortest processing time", "Critical ratio", "Slack dispatch", "Largest-demand-first", "Highest-criticality-first", "Marginal value per capacity", "Greedy set cover"], outputs: ["Dispatch sequence", "Fast incumbent", "Score decomposition", "Repair log"], validation: ["Exact small-case benchmark", "Solved-history regret", "Tie-break and failure-case tests"], limitations: "Local choices can block globally better solutions; never label optimal unless proven.", runtime: "Milliseconds to seconds", decisionShapes: ["Real-time dispatch", "Allocation", "Recovery fallback"] },
  { code: "M-10", name: "Vehicle-routing heuristics and local search", family: "Fast search & decomposition", purpose: "Construct and improve multimodal pickup, delivery, and service routes with operational constraints.", formulation: "Vehicle, visit, load, sequence, and timing decisions under capacities, time windows, access, temperature, and driver rules.", techniques: ["Sweep", "Insertion", "Clarke–Wright savings", "2-opt", "3-opt", "Relocate", "Exchange", "Cross-exchange", "Time-window repair"], outputs: ["Routes and stops", "ETAs", "Loads", "Unserved visits", "Route cost"], validation: ["Lower-bound comparison", "Best-known benchmark", "Violation register", "Exact small case"], limitations: "Road geometry and travel-time quality bound the operational accuracy of the route plan.", runtime: "Seconds to minutes", decisionShapes: ["Transport", "Last mile", "Milk runs"] },
  { code: "M-11", name: "Metaheuristics and adaptive large-neighborhood search", family: "Fast search & decomposition", purpose: "Improve large discrete plans when exact proof is too slow but strong feasible solutions matter.", formulation: "Explore domain-aware neighborhoods while preserving or repairing feasibility; embed exact matheuristic subproblems where they can strengthen the incumbent.", techniques: ["Multistart local search", "Tabu search", "Simulated annealing", "Genetic algorithms", "Memetic algorithms", "ALNS", "Ruin-and-recreate", "Fix-and-reoptimize", "Relax-and-fix", "Exact neighborhood reoptimization", "Route/pattern-pool reoptimization"], outputs: ["Best-known plan", "Improvement trace", "Multi-seed distribution", "Runtime curve"], validation: ["Multiple seeds", "Exact small cases", "Baseline regret", "Stability across runs"], limitations: "No proof of global optimality; poorly designed neighborhoods or embedded subproblems can conceal better regions.", runtime: "Seconds to hours", decisionShapes: ["Routing", "Scheduling", "Network portfolios"] },
  { code: "M-12", name: "Decomposition, column generation, and Lagrangian relaxation", family: "Fast search & decomposition", purpose: "Scale large models by separating design, recourse, periods, commodities, routes, patterns, or scenarios.", formulation: "Coordinate master and subproblems through cuts, generated columns, or relaxed prices.", techniques: ["Benders decomposition", "Column generation", "Branch-and-price", "Lagrangian relaxation", "Dantzig–Wolfe decomposition"], outputs: ["Master plan", "Cuts or columns", "Bounds", "Convergence trace", "Subproblem evidence"], validation: ["Subproblem feasibility", "Bound convergence", "Monolithic small benchmark"], limitations: "Implementation complexity and weak cuts/pricing can outweigh scale benefits.", runtime: "Minutes to hours", decisionShapes: ["Stochastic design", "Crew / route patterns", "Multi-commodity flow"] },
  { code: "M-13", name: "Single- and multi-echelon inventory optimization", family: "Inventory, flow & reliability", purpose: "Place buffers and replenishment policies across coupled echelons to meet service at minimum cost.", formulation: "Reorder points, base stocks, safety stock, order quantities, and service times under uncertain lead time and demand.", techniques: ["Newsvendor", "EOQ", "Reorder point", "Base-stock policies", "Guaranteed service-time optimization", "Risk pooling", "Cycle-service probability", "Fill rate from expected shortage"], outputs: ["Buffer placement", "Reorder policy", "Service promise", "Working-capital impact"], validation: ["Backtest cycle service and fill rate separately", "Monte Carlo policy test", "EOQ / ROP baseline comparison"], limitations: "Cycle service and fill rate are not interchangeable; service assumptions and dependency among echelons can materially change recommended stock.", runtime: "Seconds to hours", decisionShapes: ["Inventory", "Spares", "Service networks"] },
  { code: "M-14", name: "Queueing and flow analysis", family: "Inventory, flow & reliability", purpose: "Quantify congestion, wait, dwell, WIP, throughput, and utilization around constrained resources.", formulation: "Arrival and service processes, servers, queue discipline, routing, utilization, and stability conditions.", techniques: ["M/M/1 and multi-server approximations", "Kingman approximation", "Little’s Law", "Bottleneck analysis"], outputs: ["Expected wait", "Queue length", "WIP", "Utilization curve", "Bottleneck"], validation: ["Stability check", "Flow conservation", "Little’s Law reconciliation", "Empirical dwell fit"], limitations: "Stationarity and independence approximations fail during disruptions or appointment-heavy operations.", runtime: "Milliseconds to minutes", decisionShapes: ["Ports", "Warehouses", "Production cells", "Call-offs"] },
  { code: "M-15", name: "Reliability, survival, and maintenance optimization", family: "Inventory, flow & reliability", purpose: "Reduce downtime and lifecycle risk through inspection, preventive work, spares, repair, and replacement.", formulation: "Hazard, restoration, condition state, intervention, spares, and redundancy under safety rules.", techniques: ["Weibull survival", "Proportional hazards", "Renewal models", "Condition-based maintenance", "Reliability block diagrams"], outputs: ["Hazard curve", "Remaining life", "Maintenance plan", "Spare placement", "Recovery risk"], validation: ["Censoring treatment", "Historical fit", "Repair-time calibration", "Safety-rule verification"], limitations: "Sparse failures and policy-induced censoring can bias estimated hazard.", runtime: "Minutes to hours", decisionShapes: ["Maintenance", "Critical assets", "Spares"] },
  { code: "M-16", name: "Monte Carlo simulation", family: "Simulation", purpose: "Propagate correlated uncertainty through a selected plan to estimate outcome distributions and tail risk.", formulation: "Sample joint input states, replay policy, aggregate cost, service, recovery, and violations.", techniques: ["Empirical sampling", "Copulas", "Variance reduction", "Common random numbers", "Controlled seeds", "Latin hypercube"], outputs: ["P50 / P90 / P95 / P99", "CVaR", "Violation probability", "Confidence interval"], validation: ["Seed reproducibility", "Monte Carlo half-width", "Dependence tests", "Out-of-sample stress"], limitations: "A precise simulation of a misspecified distribution remains misleading.", runtime: "Seconds to hours", decisionShapes: ["Risk quantification", "Inventory", "Project and recovery risk"] },
  { code: "M-17", name: "Discrete-event simulation", family: "Simulation", purpose: "Represent queues, resources, calendars, routing, failures, and recovery in time-ordered operations.", formulation: "Entities move through event calendars and seize/release governed resources under operational logic.", techniques: ["Event scheduling", "Process interaction", "Warm-up analysis", "Independent replications", "Common random numbers"], outputs: ["Throughput", "Dwell distribution", "WIP", "Utilization", "Recovery distribution"], validation: ["Conceptual validation", "Code and conservation tests", "Warm-up / run length", "Calibration", "Operator face validation"], limitations: "Detailed simulation can be expensive to build and may encode unreviewed operating rules.", runtime: "Minutes to hours", decisionShapes: ["Warehouse", "Port", "Factory", "Transport recovery"] },
  { code: "M-18", name: "System-dynamics simulation", family: "Simulation", purpose: "Explain long-horizon stocks, flows, feedback, delays, bullwhip, investment, adoption, and policy response.", formulation: "Coupled differential/difference equations for stocks, rates, delays, and feedback loops.", techniques: ["Causal-loop diagrams", "Stock-flow models", "Delay functions", "Policy response experiments"], outputs: ["State trajectory", "Amplification", "Capacity path", "Policy comparison"], validation: ["Causal-structure review", "Historical behavior", "Extreme cases", "Parameter sensitivity"], limitations: "Aggregate behavior is useful strategically but does not schedule individual orders or assets.", runtime: "Seconds to minutes", decisionShapes: ["Strategic capacity", "Bullwhip", "Circularity"] },
  { code: "M-19", name: "Agent-based and network-contagion simulation", family: "Simulation", purpose: "Model heterogeneous actors and cascading behavior through supplier, customer, worker, or counterparty networks.", formulation: "Agents apply behavior rules and interact over typed network relationships under repeated scenarios.", techniques: ["Network diffusion", "Contagion models", "Behavioral agents", "Cascade and substitution simulation"], outputs: ["Cascade path", "Adoption / default", "Substitution", "Systemic-risk distribution"], validation: ["Network-structure check", "Emergent-pattern comparison", "Multi-seed sensitivity", "Behavioral calibration"], limitations: "Emergent results are highly sensitive to behavioral rules and incomplete network visibility.", runtime: "Minutes to hours", decisionShapes: ["N-tier risk", "Contagion", "Market response"] },
  { code: "M-20", name: "Two-stage and multistage stochastic programming", family: "Uncertainty & risk", purpose: "Choose here-and-now commitments and scenario-dependent recourse without using future information.", formulation: "First-stage design/contract/buffer decisions plus probability-weighted recourse with non-anticipativity.", techniques: ["Scenario trees", "Sample-average approximation", "Progressive hedging", "Benders decomposition", "Scenario reduction"], outputs: ["Here-and-now plan", "Scenario recourse", "EVPI", "VSS", "Regret", "Stability"], validation: ["Probability reconciliation", "Non-anticipativity test", "Held-out scenarios", "Scenario-reduction sensitivity"], limitations: "Scenario explosion and poor joint distributions can make a detailed model falsely confident.", runtime: "Minutes to hours", decisionShapes: ["Network design", "Sourcing", "Capacity", "Inventory"] },
  { code: "M-21", name: "Chance-constrained optimization", family: "Uncertainty & risk", purpose: "Require service, capacity, safety, quality, or compliance to hold with governed probability.", formulation: "Decision plan plus probabilistic constraints P(g(x,ξ)≤0)≥α and tractable approximations.", techniques: ["Analytic reformulation", "Scenario approximation", "Bonferroni allocation", "Sample constraints"], outputs: ["Required buffer", "Compliance confidence", "Empirical violation frequency", "Price of confidence"], validation: ["Tail calibration", "Achieved coverage", "Alpha sensitivity", "Out-of-sample violation rate"], limitations: "Individual chance constraints may not control simultaneous system-wide failure.", runtime: "Minutes to hours", decisionShapes: ["Service", "Capacity", "Safety stock", "Quality"] },
  { code: "M-22", name: "Robust and distributionally robust optimization", family: "Uncertainty & risk", purpose: "Retain feasibility or limit loss across bounded parameter sets or probability ambiguity sets.", formulation: "Plan, adjustable recourse, uncertainty budget, and ambiguity radius under worst-case loss/feasibility.", techniques: ["Box / budgeted uncertainty", "Ellipsoidal sets", "Wasserstein DRO", "Moment ambiguity", "Adjustable robustness"], outputs: ["Robust plan", "Worst case", "Uncertainty consumption", "Price of robustness"], validation: ["Budget / radius sensitivity", "Historical extremes", "Held-out regimes", "Set coverage"], limitations: "Over-wide sets create conservatism; narrow sets miss real compound extremes.", runtime: "Minutes to hours", decisionShapes: ["Continuity", "Capacity", "Lead-time uncertainty", "Network design"] },
  { code: "M-23", name: "CVaR and risk-averse optimization", family: "Uncertainty & risk", purpose: "Trade expected performance against the mean loss in the worst governed tail.", formulation: "Minimize expected objective + λ·CVaRα using VaR threshold and scenario excess variables.", techniques: ["Linear CVaR reformulation", "Tail contribution", "Named stress constraints", "Risk-budget tuning"], outputs: ["VaR", "CVaR", "Tail scenarios", "Tail contribution", "Efficient frontier"], validation: ["Alpha / lambda sensitivity", "Tail stability", "Named-stress replay", "Out-of-sample tail loss"], limitations: "Historical tails may be too sparse to identify compound risk without stress design.", runtime: "Minutes to hours", decisionShapes: ["Resilience", "Cash", "Margin", "Recovery"] },
  { code: "M-24", name: "Multiobjective and Pareto optimization", family: "Decision systems & governance", purpose: "Expose defensible trade-offs among service, cost, resilience, emissions, cash, safety, and social outcomes.", formulation: "Lexicographic levels, epsilon constraints, or approved normalized weights across competing objectives.", techniques: ["Lexicographic optimization", "Epsilon constraint", "Pareto frontier", "Weighted sum with sensitivity", "Knee-point analysis"], outputs: ["Pareto plans", "Dominance", "Trade-off slopes", "Selected rationale"], validation: ["Unit normalization", "Weight / epsilon sensitivity", "Hard-floor compliance", "Decision-owner review"], limitations: "A frontier informs judgment but does not decide governance preferences by itself.", runtime: "Minutes to hours", decisionShapes: ["Every material trade-off", "Portfolio", "Network design"] },
  { code: "M-25", name: "Multi-criteria decision analysis and data envelopment analysis", family: "Decision systems & governance", purpose: "Rank or benchmark suppliers, sites, technologies, and policies using explicit preference evidence.", formulation: "Criterion scores, governed weights, peer inputs/outputs, and weight bounds or consistency rules.", techniques: ["AHP-style preference evidence", "Outranking", "Utility scoring", "DEA efficiency frontier", "Rank robustness"], outputs: ["Ranking", "Score decomposition", "Peer frontier", "Rank sensitivity"], validation: ["Judgment consistency", "Stable ranking", "Feasibility cross-check", "Bias review"], limitations: "Compensatory scores must not override hard eligibility or compliance constraints.", runtime: "Seconds to minutes", decisionShapes: ["Supplier selection", "Site screening", "Technology choice"] },
  { code: "M-26", name: "Simulation-optimization, rolling horizon, and digital twins", family: "Decision systems & governance", purpose: "Continuously estimate state, generate candidates, simulate, select, execute, and replan after drift.", formulation: "Closed-loop state estimator, candidate generator, simulator, policy selector, freeze zones, and replan trigger.", techniques: ["Rolling horizon", "Simulation optimization", "Digital-twin synchronization", "Champion / challenger", "Freeze-zone control"], outputs: ["Current recommendation", "Outcome distribution", "Replan trigger", "Actual-vs-predicted learning"], validation: ["Shadow mode", "Closed-loop replay", "Synchronization test", "Fallback drill"], limitations: "A stale twin can automate yesterday’s reality; state and policy drift require active monitoring.", runtime: "Continuous / minutes", decisionShapes: ["Control tower", "Dispatch", "Integrated planning"] },
  { code: "M-27", name: "Approximate dynamic programming and reinforcement learning", family: "Decision systems & governance", purpose: "Learn long-run policies for repeated high-dimensional decisions when exact DP is infeasible.", formulation: "State, action, transition, reward, value/policy approximation, and safe-action constraints.", techniques: ["Approximate value iteration", "Policy gradients", "Offline RL", "Bandits", "Safe policy constraints"], outputs: ["Recommended action", "Value estimate", "Policy confidence", "Long-run reward"], validation: ["Simulator fidelity", "Off-policy evaluation", "Held-out episodes", "Safe fallback"], limitations: "Experimental only unless causal coverage, safety constraints, and deterministic fallback are proven.", runtime: "Hours to days training", decisionShapes: ["Repeated allocation", "Dynamic inventory", "Adaptive dispatch"] },
  { code: "M-28", name: "Design of experiments, sensitivity, and causal analysis", family: "Decision systems & governance", purpose: "Identify influential factors, interactions, elasticities, and defensible intervention effects.", formulation: "Factor settings or interventions under power, randomization, identification, and operational constraints.", techniques: ["Factorial design", "Response surfaces", "Global sensitivity", "Tornado analysis", "Difference-in-differences", "Synthetic control"], outputs: ["Effect estimate", "Confidence interval", "Response surface", "Sensitivity ranking"], validation: ["Power", "Pre-trends / placebos", "Robustness", "External validity"], limitations: "Association is not intervention effect without a credible identification strategy.", runtime: "Minutes to weeks", decisionShapes: ["Policy testing", "Parameter tuning", "Learning agenda"] },
  { code: "M-29", name: "Game theory, auctions, and contract mechanism design", family: "Decision systems & governance", purpose: "Design bids, allocations, prices, incentives, and contracts when counterparties react strategically.", formulation: "Player payoffs, bids, allocations, participation, incentive compatibility, capacity, budget, and legal constraints.", techniques: ["Nash / Stackelberg games", "Auction clearing", "Mechanism design", "Contract portfolios", "Cooperative allocation"], outputs: ["Clearing result", "Contract portfolio", "Equilibrium behavior", "Partner payoff"], validation: ["Equilibrium sensitivity", "Pilot behavior", "Parameter stress", "Legal review"], limitations: "Observed behavior may depart from rational-player assumptions and legal boundaries dominate design.", runtime: "Minutes to hours", decisionShapes: ["Procurement", "Carrier allocation", "Collaboration"] },
  { code: "M-30", name: "Statistical quality and acceptance sampling", family: "Decision systems & governance", purpose: "Balance inspection cost and escape risk while detecting process drift at governed error rates.", formulation: "Sample size, control limit, inspection intensity, accept/reject, quarantine, and CAPA trigger.", techniques: ["Acceptance sampling", "Operating-characteristic curves", "CUSUM / EWMA", "Process capability", "Sequential testing"], outputs: ["Accept / quarantine", "Control signal", "Defect escape risk", "CAPA queue"], validation: ["OC-curve behavior", "False-alarm / miss rate", "Historical detection replay", "Gauge quality"], limitations: "Sampling never eliminates risk and should not substitute for process capability improvement.", runtime: "Seconds to minutes", decisionShapes: ["Quality release", "Incoming inspection", "Supplier controls"] },
];

export type ProbabilityModelControl = {
  behavior: string;
  candidates: readonly string[];
  typicalUses: readonly string[];
  assumptionControls: readonly string[];
};

export const probabilityModelControls: readonly ProbabilityModelControl[] = [
  {
    behavior: "Nonnegative continuous amount",
    candidates: ["Gamma", "Lognormal", "Weibull", "Empirical / quantile"],
    typicalUses: ["Demand size", "Lead time", "Repair time", "Cost", "Dwell"],
    assumptionControls: ["Skew", "Tail fit", "Zero mass", "Censoring"],
  },
  {
    behavior: "Count per interval",
    candidates: ["Poisson", "Negative binomial", "Zero-inflated count model"],
    typicalUses: ["Orders", "Failures", "Defects", "Incidents"],
    assumptionControls: ["Overdispersion", "Changing exposure", "Zero inflation", "Nonstationarity"],
  },
  {
    behavior: "Bounded rate or share",
    candidates: ["Beta", "Empirical bounded distribution"],
    typicalUses: ["Yield", "Utilization", "Defect rate", "OTIF", "Allocation share"],
    assumptionControls: ["Preserve the [0,1] support", "Retain denominator and exposure", "Check boundary mass"],
  },
  {
    behavior: "Binary or governed status",
    candidates: ["Bernoulli", "Logistic", "Markov state"],
    typicalUses: ["Supplier availability", "Qualification", "Closure", "Control activation"],
    assumptionControls: ["State persistence", "Common-cause dependence", "Class imbalance", "Transition stability"],
  },
  {
    behavior: "Time to event",
    candidates: ["Exponential", "Weibull", "Lognormal", "Survival model"],
    typicalUses: ["Failure", "Repair", "Switching", "Recovery"],
    assumptionControls: ["Censored observations", "Hazard shape", "Competing risks", "Policy-induced censoring"],
  },
  {
    behavior: "Correlated vector",
    candidates: ["Empirical scenarios", "Copula", "Factor model", "Regime model"],
    typicalUses: ["Demand-price", "Supplier-region", "Route-weather", "Cost-FX"],
    assumptionControls: ["Cross-variable dependence", "Temporal dependence", "Joint-tail preservation", "Regime stability"],
  },
];

export type DecisionPattern = {
  id: string;
  name: string;
  question: string;
  horizons: readonly string[];
  primary: readonly ORMethod["code"][];
  supporting: readonly ORMethod["code"][];
  fallback: ORMethod["code"];
  handbookRefs: readonly string[];
};

export const decisionPatterns: readonly DecisionPattern[] = [
  { id: "allocation", name: "Demand allocation & order promising", question: "Which demand should be served from which supply, when, and at what service promise?", horizons: ["Operational", "Real-time"], primary: ["M-05", "M-06"], supporting: ["M-08", "M-13", "M-17", "M-20"], fallback: "M-09", handbookRefs: ["Table 3: demand allocation / order promising", "Appendix A: L1-036 and L1-037"] },
  { id: "network", name: "Network & facility design", question: "Which sites, lanes, capacities, and buffers should exist?", horizons: ["Strategic", "Tactical"], primary: ["M-06"], supporting: ["M-05", "M-20", "M-22", "M-24"], fallback: "M-09", handbookRefs: ["Table 3: network and facility design", "Appendix A: L1-055"] },
  { id: "sourcing", name: "Strategic sourcing", question: "How should awards, contracts, and capacity reservations be split?", horizons: ["Strategic", "Tactical"], primary: ["M-06"], supporting: ["M-20", "M-22", "M-24", "M-25", "M-29"], fallback: "M-09", handbookRefs: ["Table 3: strategic sourcing", "Appendix A: L1-006 and L1-008"] },
  { id: "production", name: "Production & lot sizing", question: "What should each plant make, in which lot, and in which period?", horizons: ["Tactical", "Operational"], primary: ["M-06"], supporting: ["M-07", "M-08", "M-20"], fallback: "M-09", handbookRefs: ["Table 3: production planning / lot sizing", "Appendix A: L1-010 and L1-011"] },
  { id: "scheduling", name: "Detailed scheduling", question: "How should jobs, labor, and constrained equipment be sequenced?", horizons: ["Operational", "Real-time"], primary: ["M-08"], supporting: ["M-06", "M-11", "M-17"], fallback: "M-09", handbookRefs: ["Table 3: detailed scheduling", "Appendix A: L1-010, L1-011, and L1-013"] },
  { id: "inventory", name: "Multi-echelon inventory", question: "Where should buffers sit and which replenishment policy should govern them?", horizons: ["Tactical", "Operational"], primary: ["M-13"], supporting: ["M-07", "M-20", "M-22"], fallback: "M-09", handbookRefs: ["Table 3: multi-echelon inventory", "Appendix A: L1-019"] },
  { id: "transport", name: "Transport planning", question: "Which mode, carrier, route, and departure should move each commitment?", horizons: ["Operational", "Real-time"], primary: ["M-05", "M-10"], supporting: ["M-11", "M-17", "M-20", "M-22", "M-26"], fallback: "M-09", handbookRefs: ["Table 3: transport planning", "Appendix A: L1-026 through L1-034"] },
  { id: "warehouse", name: "Warehouse operations", question: "How should waves, doors, labor, slots, and material handling be assigned?", horizons: ["Operational", "Real-time"], primary: ["M-08"], supporting: ["M-10", "M-14", "M-17"], fallback: "M-09", handbookRefs: ["Table 3: warehouse operations", "Appendix A: L1-021 through L1-025"] },
  { id: "workforce", name: "Workforce planning", question: "Which skills and shifts are required to meet service and safety?", horizons: ["Tactical", "Operational"], primary: ["M-08"], supporting: ["M-06", "M-16", "M-24"], fallback: "M-09", handbookRefs: ["Table 3: workforce planning", "Appendix A: L1-014"] },
  { id: "maintenance", name: "Maintenance & spares", question: "When should assets be maintained and where should recovery spares be placed?", horizons: ["Tactical", "Operational"], primary: ["M-15"], supporting: ["M-06", "M-07", "M-17"], fallback: "M-09", handbookRefs: ["Table 3: maintenance and spares", "Appendix A: L1-012"] },
  { id: "reverse", name: "Reverse & circular flow", question: "Which returns should be repaired, reused, recycled, or disposed through which path?", horizons: ["Strategic", "Tactical"], primary: ["M-05", "M-06"], supporting: ["M-08", "M-10", "M-17", "M-24"], fallback: "M-09", handbookRefs: ["Table 3: reverse and circular flow", "Appendix A: L1-039, L1-040, and L1-052"] },
  { id: "portfolio", name: "Cash, carbon & resilience portfolio", question: "Which actions jointly protect value within cash, carbon, and risk appetite?", horizons: ["Strategic", "Tactical"], primary: ["M-06", "M-24"], supporting: ["M-05", "M-16", "M-20", "M-21", "M-22", "M-23", "M-26"], fallback: "M-09", handbookRefs: ["Table 3: cash, carbon, and resilience portfolio", "Appendix A: L1-042, L1-050, L1-051, and L1-055"] },
];

export type ConstraintFamily = { id: string; name: string; example: string; count: number; hard: boolean; owner: string };
export const constraintFamilies: readonly ConstraintFamily[] = [
  { id: "C-01", name: "Inventory flow balance", example: "Opening + receipts + production − demand − shipments = closing inventory", count: 7, hard: true, owner: "Network planning" },
  { id: "C-02", name: "Production & material balance", example: "Output cannot exceed BOM-feasible material conversion and yield", count: 6, hard: true, owner: "Manufacturing" },
  { id: "C-03", name: "Supplier & allocation capacity", example: "Awards remain inside qualified and reserved capacity bands", count: 5, hard: true, owner: "Procurement" },
  { id: "C-04", name: "Lane & asset capacity", example: "Weight, cube, TEU, flight, truck, and rail slots remain feasible", count: 6, hard: true, owner: "Logistics" },
  { id: "C-05", name: "Storage & handling", example: "Warehouse zones, doors, labor, and special handling stay within limits", count: 4, hard: true, owner: "Operations" },
  { id: "C-06", name: "Customer service", example: "Priority-class fill and OTIF remain above governed floors", count: 5, hard: true, owner: "Customer operations" },
  { id: "C-07", name: "MOQ, batch & setup", example: "Orders respect lot multiples, setup activation, and campaign rules", count: 4, hard: false, owner: "Manufacturing" },
  { id: "C-08", name: "Shelf life & age", example: "Age at delivery remains inside product and customer policy", count: 3, hard: true, owner: "Quality" },
  { id: "C-09", name: "Authorization & market access", example: "Only approved part-supplier-site-lane-market combinations may flow", count: 5, hard: true, owner: "Compliance" },
  { id: "C-10", name: "Carbon & resource", example: "Plan remains inside carbon, energy, water, and material envelopes", count: 4, hard: true, owner: "Sustainability" },
  { id: "C-11", name: "Cash & budget", example: "Incremental response spend and working capital remain within authority", count: 4, hard: true, owner: "Finance" },
  { id: "C-12", name: "Non-anticipativity", example: "Decisions made before uncertainty resolves cannot use future information", count: 4, hard: true, owner: "OR governance" },
];

export const uncertaintyScenarios = [
  ["S-01", "Baseline trajectory", .24, "Demand +2%; capacity nominal; Red Sea transit +8h", "Reference recourse"],
  ["S-02", "Graphite capacity loss", .12, "Supplier capacity −32% for 14 weeks", "Reserve alternate source"],
  ["S-03", "Red Sea closure", .08, "Suez unavailable; ocean lead time +12 days", "Cape reroute + inventory bridge"],
  ["S-04", "Compound port congestion", .09, "Singapore and Rotterdam dwell +36h", "Protect cutoffs and rebalance"],
  ["S-05", "Electronics upside", .11, "Customer demand +14%; price +3%", "Prioritize margin and air slots"],
  ["S-06", "Launch downside", .08, "Launch slips six weeks; demand −18%", "Defer lots and release cash"],
  ["S-07", "Quality quarantine", .06, "Controller lot quarantine; yield −9 points", "Switch qualified BOM path"],
  ["S-08", "Energy price shock", .06, "EU power +28%; conversion cost +7%", "Shift production window"],
  ["S-09", "Carrier capacity squeeze", .05, "Ocean slots −20%; spot freight +35%", "Use protected capacity"],
  ["S-10", "FX and duty shock", .04, "EUR/USD −7%; duty +4 points", "Re-rank landed-cost sources"],
  ["S-11", "Cyber recovery", .04, "Plant planning interface unavailable 48h", "Freeze plan + manual fallback"],
  ["S-12", "Coordinated recovery", .03, "Alternate qualification early; congestion clears", "Reduce expedites and tail risk"],
] as const;

export const validationGates = [
  { id: "semantic", name: "Semantic", question: "Are grain, units, time, provenance, ownership, and decision roles unambiguous?", evidence: "Variable registry, reconciliation, source contracts", state: "Passed" },
  { id: "mathematical", name: "Mathematical", question: "Is the formulation feasible, bounded, reproducible, and internally consistent?", evidence: "Residuals, hard constraints, candidate membership", state: "Passed" },
  { id: "empirical", name: "Empirical", question: "Does the policy outperform baselines on held-out history and named stresses?", evidence: "Replay, calibration, sensitivity, champion/challenger", state: "Review" },
  { id: "operational", name: "Operational", question: "Can people execute, monitor, override, and safely fall back?", evidence: "Owner acceptance, frozen zone, fallback drill, approvals", state: "Review" },
] as const;

export const solutionEvidenceBlocks = [
  ["Feasibility", "Hard violations, residuals, eligibility, conservation and release state"],
  ["Solution quality", "Baseline, incumbent, legitimate bound/gap, Pareto dominance and regret"],
  ["Risk", "P50/P90/P95/P99, CVaR, named stresses, recovery and violation probability"],
  ["Stability", "Plan churn, frozen decisions, owner disruption and sensitivity"],
  ["Performance", "Runtime, candidates/nodes/scenarios, memory and timeout behavior"],
  ["Reproducibility", "Input fingerprint, model/data versions, seed and settings"],
  ["Explainability", "Binding constraints, shadow prices, objective decomposition and rejected alternatives"],
] as const;

export function getMethod(code: ORMethod["code"]) {
  return orMethods.find((method) => method.code === code);
}
