"use client";

import { useState } from "react";
import { fixtureEvidenceFor, projectApps, type EvidenceReceipt, type ProjectAppId, type WorkspaceProject } from "./workspace-model";
import { AppGlyph } from "./VisualIdentity";

type Props = {
  appId: ProjectAppId;
  project: WorkspaceProject;
  onEvidence: (receipt: EvidenceReceipt) => void;
  onOutcome: (title: string, detail: string, artifact?: string) => void;
};

function StudioHeader({ appId, project }: Pick<Props, "appId" | "project">) {
  const app = projectApps.find((item) => item.id === appId) ?? projectApps[0];
  return <header className="studio-header app-canonical-header">
    <div><AppGlyph appId={appId} className="app-code" /><p>PROJECT APP · {project.code}</p><h1>{app.name}</h1><small>{app.archetype} · {app.outcome}</small></div>
    <aside><b>{app.status}</b><span>{app.methodCodes.join(" · ")}</span><small>Deterministic demonstration data</small></aside>
  </header>;
}

function EvidenceMetric({ project, app, id, label, value, detail, variableId, onEvidence }: { project: WorkspaceProject; app: string; id: string; label: string; value: string; detail: string; variableId?: string; onEvidence: Props["onEvidence"] }) {
  const receipt = fixtureEvidenceFor(project, { id: `EV-${app}-${id}`, claim: label, displayedValue: value, source: `${app} deterministic demonstration fixture`, formula: detail, variableId });
  return <button className="studio-metric" data-action-id={`evidence.open.${receipt.id}`} type="button" onClick={() => onEvidence(receipt)}><span>{label}</span><b>{value}</b><small>{detail}</small><em>◇ {receipt.id}</em></button>;
}

function MineralAtlas({ project, onEvidence, onOutcome }: Omit<Props, "appId">) {
  const [mineral, setMineral] = useState("Graphite");
  const [country, setCountry] = useState("China");
  const [scenario, setScenario] = useState("Policy stress");
  const minerals: Record<string, { reserve: string; share: string; price: string; constraint: string }> = {
    Graphite: { reserve: "73.4 Mt", share: "71%", price: "$1,840/t", constraint: "Qualified spherical refining" }, Lithium: { reserve: "28.6 Mt", share: "46%", price: "$13,420/t", constraint: "Conversion + water stress" }, Copper: { reserve: "890 Mt", share: "31%", price: "$9,120/t", constraint: "Mine grade + grid demand" }, "Rare earths": { reserve: "118 Mt", share: "69%", price: "$58/kg", constraint: "Separation capacity" },
  };
  const countries = [["China",78,92,"Refining"],["Mozambique",64,78,"Mine"],["Madagascar",58,74,"Mine"],["Brazil",42,82,"Reserve"],["Vietnam",36,68,"Alternate"]] as const;
  const selected = minerals[mineral];
  return <div className="mineral-studio">
    <section className="studio-toolbar"><div>{Object.keys(minerals).map((item) => <button data-action-id={`minerals.select.${item}`} className={mineral === item ? "active" : ""} type="button" key={item} onClick={() => setMineral(item)}>{item}</button>)}</div><label>Scenario<select value={scenario} onChange={(event) => setScenario(event.target.value)}><option>Policy stress</option><option>Demand surge</option><option>Water constraint</option><option>Balanced transition</option></select></label><button data-action-id="minerals.create-scenario" type="button" onClick={() => onOutcome("Mineral scenario receipt recorded", `${mineral} · ${scenario} parameters were recorded in the browser-session ledger for ${project.client} / ${project.name}; no scenario was created, saved, or routed.`, `${project.code}-MIN-SCENARIO-${mineral.toUpperCase().slice(0,3)}-04`)}>Record sourcing-scenario receipt →</button></section>
    <div className="studio-metrics"><EvidenceMetric project={project} app="MINERAL" id={`${mineral}-RESERVES`} label="Fixture reserves" value={selected.reserve} detail={`${mineral} country-balance fixture sum`} variableId="L0-030" onEvidence={onEvidence} /><EvidenceMetric project={project} app="MINERAL" id={`${mineral}-REFINING-SHARE`} label="Largest refining share" value={selected.share} detail={`${selected.constraint} fixture share`} variableId="L0-030" onEvidence={onEvidence} /><EvidenceMetric project={project} app="MINERAL" id={`${mineral}-REFERENCE-COST`} label="Reference cost" value={selected.price} detail="Illustrative delivered-cost basis; no market feed" variableId="L0-043" onEvidence={onEvidence} /><EvidenceMetric project={project} app="MINERAL" id="TRACEABLE-VOLUME" label="Traceable project volume" value="82%" detail={`${project.name} synthetic evidence coverage`} variableId="L0-052" onEvidence={onEvidence} /></div>
    <div className="mineral-layout"><section className="mineral-map"><header><div><p>RESERVE → REFINERY → PRODUCT</p><h2>{mineral} control atlas</h2></div><span>DEMO COUNTRY FIXTURE · NO LIVE FEED</span></header><div className="mineral-world" aria-label="Synthetic mineral country network"><i className="min-route r1" /><i className="min-route r2" /><i className="min-route r3" />{countries.map((item, index) => <button data-action-id={`minerals.country.${item[0]}`} type="button" className={`min-country c${index + 1} ${country === item[0] ? "active" : ""}`} key={item[0]} onClick={() => setCountry(item[0])}><b>{item[0]}</b><span>{item[1]} score</span></button>)}</div><footer><span>Mine / reserve</span><span>Refinery</span><span>Controlled route</span><b>{country} selected · {scenario}</b></footer></section>
      <aside className="mineral-balance"><header><p>COUNTRY DOSSIER</p><h2>{country}</h2><span>{mineral} · synthetic evidence</span></header>{[["Resource position",country === "China" ? "Top quartile" : "Emerging"],["Controlled capacity",country === "China" ? "71%" : "14%"],["Policy exposure","Medium-high"],["Water / rights review","Required"],[`Route to ${project.regions.split("·")[0]?.trim()}`,country === "Brazil" ? "34 days" : "18 days"]].map((row) => { const receipt = fixtureEvidenceFor(project, { id: `EV-MINERAL-${mineral}-${country}-${row[0]}`, claim: `${country} ${row[0]}`, displayedValue: row[1], source: "MineralAtlas country-dossier demonstration fixture", formula: `${scenario} fixture lookup for ${mineral} in ${country}`, variableId: row[0] === "Controlled capacity" ? "L0-030" : undefined }); return <button data-action-id={`minerals.trace.${row[0]}`} type="button" key={row[0]} onClick={() => onEvidence(receipt)}><span>{row[0]}</span><b>{row[1]}</b><em>◇</em></button>; })}<div><p>HARD GATES</p><span>Origin eligible</span><span>Rights evidence current</span><span>Water scenario inside limit</span><span>Qualified material grade</span></div></aside>
    </div>
  </div>;
}

function WorkforceStudio({ project, onEvidence, onOutcome }: Omit<Props, "appId">) {
  const [scenario, setScenario] = useState("Recovery roster");
  const skills = [[`${project.sector} constraint operator`,18,16,89],[`${project.name} release analyst`,12,12,100],[`${project.regions.split("·")[0]?.trim()} logistics coordinator`,8,6,75],["Maintenance electrician",14,11,79],["Safety and compliance lead",5,5,100]] as const;
  const [selectedSkill, setSelectedSkill] = useState<string>(skills[0][0]);
  return <div className="workforce-studio">
    <section className="studio-toolbar"><div>{["Baseline", "Recovery roster", "Surge + overtime", "Fatigue-safe"].map((item) => <button data-action-id={`workforce.scenario.${item}`} className={scenario === item ? "active" : ""} type="button" key={item} onClick={() => setScenario(item)}>{item}</button>)}</div><button data-action-id="workforce.commit-plan" type="button" onClick={() => onOutcome("Workforce-plan receipt recorded", `${scenario} parameters were recorded in the browser-session ledger for OR scientist and safety review; no capacity plan was saved, staged, or routed.`, `${project.code}-WORKFORCE-PLAN-V7`)}>Record capacity-plan receipt →</button></section>
    <div className="studio-metrics"><EvidenceMetric project={project} app="WORKFORCE" id={`${scenario}-COVERAGE`} label="Qualified coverage" value="89%" detail="Qualified people / required roles across the next 21 fixture shifts" onEvidence={onEvidence} /><EvidenceMetric project={project} app="WORKFORCE" id={`${scenario}-OPEN-HOURS`} label="Open skill hours" value="428h" detail="Sum of uncovered constraint-skill hours in the roster fixture" onEvidence={onEvidence} /><EvidenceMetric project={project} app="WORKFORCE" id={`${scenario}-FATIGUE`} label="Fatigue breaches" value={scenario === "Surge + overtime" ? "7" : "0"} detail="Fixture count breaching the hard fatigue rule" onEvidence={onEvidence} /><EvidenceMetric project={project} app="WORKFORCE" id={`${scenario}-COST`} label="Plan cost" value="$186K" detail="Illustrative premium labor plus travel cost" onEvidence={onEvidence} /></div>
    <div className="workforce-layout"><section className="skills-matrix"><header><p>SKILL × SHIFT COVERAGE</p><h2>{scenario}</h2><span>Availability, certification, fatigue, and site access are separate constraints.</span></header><div className="skills-table"><div className="skills-row head"><span>Critical skill</span><b>Required</b><b>Qualified</b><b>Coverage</b></div>{skills.map((skill) => <button data-action-id={`workforce.skill.${skill[0]}`} className={`skills-row ${selectedSkill === skill[0] ? "active" : ""}`} type="button" key={skill[0]} onClick={() => setSelectedSkill(skill[0])}><span>{skill[0]}</span><b>{skill[1]}</b><b>{skill[2]}</b><strong>{skill[3]}%</strong></button>)}</div><div className="shift-heatmap">{Array.from({ length: 42 }, (_, index) => <button data-action-id={`workforce.shift.${index + 1}`} type="button" key={index} className={index % 11 === 0 ? "gap" : index % 7 === 0 ? "watch" : "covered"} onClick={() => onOutcome("Shift-cell receipt recorded", `Shift ${index + 1} · ${selectedSkill} · ${index % 11 === 0 ? "coverage gap" : "covered"} was recorded as a browser-session fixture reference; no roster or assignment changed.`, `${project.code}-SHIFT-${String(index + 1).padStart(2,"0")}`)} aria-label={`Shift ${index + 1}`} />)}</div></section>
      <aside className="workforce-card"><p>SELECTED CAPABILITY</p><h2>{selectedSkill}</h2><span>Project-specific human capacity, not a generic headcount.</span><dl><div><dt>Current qualified</dt><dd>16 people</dd></div><div><dt>Certificate expiry</dt><dd>2 in 30 days</dd></div><div><dt>Travel-ready</dt><dd>11 people</dd></div><div><dt>Lead time to qualify</dt><dd>6 weeks</dd></div></dl><button data-action-id="workforce.trace-capability" type="button" onClick={() => onEvidence(fixtureEvidenceFor(project, { id: `EV-WORKFORCE-${selectedSkill}`, claim: `${selectedSkill} capacity profile`, displayedValue: "16 qualified · 11 travel-ready", source: "WorkforceStudio deterministic capability fixture", formula: "Selected skill, certification, availability, travel-readiness, and qualification-lead-time fixture", inputs: ["16 qualified", "2 expiries in 30 days", "11 travel-ready", "6-week lead time"] }))}>Trace capability profile ◇</button><button data-action-id="workforce.assign-expert" type="button" onClick={() => onOutcome("Specialist-assignment draft receipt recorded", `${selectedSkill} and the Workforce Capacity Analyst were recorded as a proposed browser-session assignment; no agent or person was assigned and no shadow workflow started.`, `${project.code}-ASSIGNMENT-WF-18`)}>Record specialist-assignment draft</button></aside></div>
  </div>;
}

function ManufacturingTwin({ project, onEvidence, onOutcome }: Omit<Props, "appId">) {
  const [plan, setPlan] = useState("Recovery plan");
  const cells = [[`${project.name} input`,92,"healthy"],[`${project.sector} constraint`,104,"critical"],["Primary process",86,"watch"],["Quality gate",78,"healthy"],["Pack and release",96,"watch"]] as const;
  const [cell, setCell] = useState<string>(cells[1][0]);
  return <div className="manufacturing-studio">
    <section className="studio-toolbar"><div>{["Baseline", "Recovery plan", "Service first", "Low-carbon"].map((item) => <button data-action-id={`manufacturing.plan.${item}`} className={plan === item ? "active" : ""} type="button" key={item} onClick={() => setPlan(item)}>{item}</button>)}</div><button data-action-id="manufacturing.simulate" type="button" onClick={() => onOutcome("DES fixture replayed", `${plan} displayed the stored 40-replication demonstration summary; no simulation engine or plant system was contacted.`, "SIM-FIXTURE-DES-040")}>Replay 40-replication DES fixture →</button></section>
    <div className="studio-metrics"><EvidenceMetric project={project} app="MANUFACTURING" id={`${plan}-UTILIZATION`} label="Constraint utilization" value="104%" detail={`Fixture load / effective capacity at ${cells[1][0]}`} onEvidence={onEvidence} /><EvidenceMetric project={project} app="MANUFACTURING" id={`${plan}-ATTAINMENT`} label="Plan attainment" value="91.8%" detail={`${plan} fixture completed quantity / planned quantity`} onEvidence={onEvidence} /><EvidenceMetric project={project} app="MANUFACTURING" id={`${plan}-WIP`} label="WIP" value="1,842 t" detail="Synthetic work-in-process sum across five process steps" onEvidence={onEvidence} /><EvidenceMetric project={project} app="MANUFACTURING" id={`${plan}-OUTPUT`} label="Expected output" value="14.6K" detail="Qualified units per week in the deterministic plan fixture" onEvidence={onEvidence} /></div>
    <div className="manufacturing-layout"><section className="plant-flow"><header><p>PLANT FLOW · CONSTRAINT VIEW</p><h2>{project.client} · {plan}</h2></header><div className="plant-cells">{cells.map((item, index) => <button data-action-id={`manufacturing.cell.${item[0]}`} className={`${item[2]} ${cell === item[0] ? "active" : ""}`} type="button" key={item[0]} onClick={() => setCell(item[0])}><span>0{index + 1}</span><b>{item[0]}</b><strong>{item[1]}%</strong><small>{item[2]} capacity</small></button>)}</div><div className="gantt"><header><span>W36</span><span>W37</span><span>W38</span><span>W39</span><span>W40</span></header>{[72,88,54,94,66].map((width,index) => <button data-action-id={`manufacturing.gantt.${index + 1}`} type="button" key={index} onClick={() => setCell(cells[index][0])}><span style={{ width: `${width}%` }}>{cells[index][0]} · lot {index + 18}</span></button>)}</div></section>
      <aside className="machine-inspector"><p>BOTTLENECK INSPECTOR</p><h2>{cell}</h2><span>Discrete-event fixture · current selection</span><dl><div><dt>Rated capacity</dt><dd>16.2K / week</dd></div><div><dt>Effective capacity</dt><dd>14.1K / week</dd></div><div><dt>Yield</dt><dd>97.4%</dd></div><div><dt>Unplanned downtime</dt><dd>6.8h</dd></div><div><dt>Queue P90</dt><dd>11.4h</dd></div></dl><button data-action-id="manufacturing.trace-cell" type="button" onClick={() => onEvidence(fixtureEvidenceFor(project, { id: `EV-MANUFACTURING-${cell}`, claim: `${cell} bottleneck profile`, displayedValue: "14.1K/week effective · 97.4% yield", source: "ManufacturingTwin deterministic cell fixture", formula: "Rated capacity adjusted by fixture uptime, yield, and queue assumptions", inputs: ["16.2K/week rated", "6.8h downtime", "11.4h queue P90"] }))}>Trace bottleneck profile ◇</button><button data-action-id="manufacturing.create-work-order" type="button" onClick={() => onOutcome("Maintenance draft receipt recorded", `${cell} constraint work-package parameters were recorded for human review in the browser-session ledger; no work order was created.`, `WORK-PACKAGE-${project.code}-MT-204`)}>Draft constraint work package</button></aside></div>
  </div>;
}

function LogisticsRadar({ project, onEvidence, onOutcome }: Omit<Props, "appId">) {
  const projectRegions = project.regions.split("·").map((item) => item.trim());
  const assets = [[`${project.code}-VESSEL-01`,"Vessel","812 TEU","+3.4d"],[`${project.code}-AIR-071`,"Flight","42 lots","On plan"],[`${project.code}-RAIL-184`,"Rail","186 t","+4h"],[`${project.code}-ROAD-882`,"Truck","24 pallets","At gate"]] as const;
  const [asset, setAsset] = useState<string>(assets[0][0]);
  const [frame, setFrame] = useState("Now");
  return <div className="logistics-studio">
    <section className="studio-toolbar"><div>{["Now", "+24h", "+7d", "+30d"].map((item) => <button data-action-id={`logistics.frame.${item}`} className={frame === item ? "active" : ""} type="button" key={item} onClick={() => setFrame(item)}>{item}</button>)}</div><button data-action-id="logistics.release-route" type="button" onClick={() => onOutcome("Route-package draft recorded", `${asset} · ${frame} route parameters were retained in the session receipt ledger for port-controller review; no route was released.`, `ROUTE-PACKAGE-${project.code}-LR-71`)}>Draft route package →</button></section>
    <div className="studio-metrics"><EvidenceMetric project={project} app="LOGISTICS" id="GOODS-IN-MOTION" label="Goods in motion" value={project.metrics[0].value} detail={`${project.counts.events} synthetic event-metadata records`} onEvidence={onEvidence} /><EvidenceMetric project={project} app="LOGISTICS" id="DELAYED-CARGO" label="Delayed cargo" value={project.metrics[1].value} detail={`${project.metrics[1].label} project fixture`} onEvidence={onEvidence} /><EvidenceMetric project={project} app="LOGISTICS" id="TRANSFER-DWELL" label="Transfer dwell" value={project.metrics[3].value} detail={`${project.regions} deterministic route fixture`} onEvidence={onEvidence} /><EvidenceMetric project={project} app="LOGISTICS" id="SIGNED-HANDOFFS" label="Signed handoffs" value="98.7%" detail="Valid signature events / synthetic QR handoff events" onEvidence={onEvidence} /></div>
    <div className="logistics-layout"><section className="logistics-map"><header><div><p>MULTIMODAL RADAR · {frame.toUpperCase()}</p><h2>{project.name} · berth to door</h2></div><span>SIMULATED TELEMETRY · NO AIS / ADS-B CONNECTION</span></header><div className="radar-grid"><i className="sea-route s1" /><i className="sea-route s2" /><i className="road-route" />{assets.map((item,index) => <button data-action-id={`logistics.asset.${item[0]}`} className={`radar-vehicle v${index + 1} ${asset === item[0] ? "active" : ""}`} type="button" key={item[0]} onClick={() => setAsset(item[0])}><span>{item[1]}</span><b>{item[0]}</b></button>)}{projectRegions.slice(0,4).map((region,index) => { const code = region.replace(/[^A-Za-z]/g, "").slice(0,3).toUpperCase() || `H${index+1}`; const positions = [[68,58],[47,70],[37,56],[12,31]][index]; return <button data-action-id={`logistics.node.${code}`} className="radar-hub" style={{left:`${positions[0]}%`,top:`${positions[1]}%`}} type="button" key={`${region}-${index}`} onClick={() => onOutcome("Hub fixture inspected", `${region} synthetic transfer and capacity record was referenced in the session receipt ledger.`, `HUB-${project.code}-${code}`)}><b>{code}</b><span>{region}</span></button>; })}</div><footer><span>Ocean route</span><span>Air bridge</span><span>Road transfer</span><b>Scroll and zoom remain in the global Network Radar</b></footer></section>
      <aside className="asset-radar-card"><p>SELECTED ASSET</p><h2>{asset}</h2>{assets.filter((item) => item[0] === asset).map((item) => <div key={item[0]}><span>{item[1]} · {project.code} synthetic identifier</span><dl><div><dt>Quantity</dt><dd>{item[2]}</dd></div><div><dt>ETA variance</dt><dd>{item[3]}</dd></div><div><dt>Project signal</dt><dd>{project.metrics[0].value}</dd></div><div><dt>Evidence claims</dt><dd>{project.counts.claims}</dd></div><div><dt>Owner</dt><dd>{project.owner}</dd></div></dl><button data-action-id="logistics.trace-asset" type="button" onClick={() => onEvidence(fixtureEvidenceFor(project, { id: `EV-LOGISTICS-${item[0]}`, claim: `${item[0]} movement profile`, displayedValue: `${item[2]} · ${item[3]}`, source: "LogisticsRadar simulated telemetry fixture", formula: `${frame} asset-state lookup; no AIS, ADS-B, carrier, or device feed`, inputs: [project.metrics[0].evidenceRef, `${project.counts.claims} project claim metadata`] }))}>Trace asset evidence ◇</button></div>)}<button data-action-id="logistics.scan-qr" type="button" onClick={() => onOutcome("QR handoff receipt recorded", `A GS1 Digital Link-style demonstration payload was recorded only in the browser-session receipt ledger for ${project.client} / ${project.name}; no signature was verified and no device or external system was contacted.`, `EVENT-${project.code}-QR-01`)}>Simulate secure QR handoff</button></aside></div>
  </div>;
}

function QualityGenealogy({ project, onEvidence, onOutcome }: Omit<Props, "appId">) {
  const batches = [`${project.code}-SOURCE-44`, `${project.code}-PROCESS-21`, `${project.code}-RELEASE-84`, `${project.code}-CUSTOMER-71`];
  const [batch, setBatch] = useState(batches[0]);
  return <div className="quality-studio"><section className="studio-toolbar"><div>{batches.map((item) => <button data-action-id={`quality.batch.${item}`} className={batch === item ? "active" : ""} type="button" key={item} onClick={() => setBatch(item)}>{item}</button>)}</div><button data-action-id="quality.release-review" type="button" onClick={() => onOutcome("Quality-review receipt recorded", `${batch} release-gate and genealogy fixture details were recorded in the browser-session ledger for ${project.client}; no review was opened and no batch state was frozen or released.`, `${project.code}-QUALITY-REVIEW-01`)}>Record release-review receipt →</button></section><div className="quality-genealogy">{batches.map((item,index) => { const stage = ["Source lot","Process batch","Release lot","Customer unit"][index]; const state = index === 1 ? "Deviation linked" : "Released"; return <button data-action-id={`quality.trace.${item}`} type="button" className={batch === item ? "active" : ""} key={item} onClick={() => { setBatch(item); onEvidence(fixtureEvidenceFor(project, { id: `EV-QUALITY-${item}`, claim: `${item} genealogy state`, displayedValue: state, source: "QualityGenealogy deterministic batch fixture", formula: `${stage} relationship and release-state lookup`, inputs: [item, stage, project.metrics[1].evidenceRef] })); }}><span>0{index+1}</span><b>{item}</b><small>{stage}</small><em>{state}</em></button>; })}</div><section className="quality-inspector"><p>GENEALOGY CONTRACT · {project.code}</p><h2>{batch}</h2><span>Every batch relationship retains certificates, test results, transformations, timestamps, and release authority.</span><dl><div><dt>Certificate coverage</dt><dd>100%</dd></div><div><dt>Open deviations</dt><dd>1</dd></div><div><dt>Affected metric</dt><dd>{project.metrics[1].value}</dd></div><div><dt>Trace depth</dt><dd>4 levels</dd></div></dl><button data-action-id="quality.trace-summary" type="button" onClick={() => onEvidence(fixtureEvidenceFor(project, { id: `EV-QUALITY-SUMMARY-${batch}`, claim: `${batch} trace summary`, displayedValue: "100% certificate coverage · 1 open deviation · 4 levels", source: "QualityGenealogy deterministic batch fixture", formula: "Fixture certificate coverage, deviation count, and relationship depth", inputs: [batch, project.metrics[1].evidenceRef] }))}>Trace summary evidence ◇</button></section></div>;
}

function UnsupportedStudio({ project, appId }: Pick<Props, "project" | "appId">) {
  return <section className="unsupported-studio"><p>PROJECT APP</p><h2>{projectApps.find((item) => item.id === appId)?.name}</h2><span>{project.client} / {project.name} remains in the active project context. Use the persistent Back to project control above to return.</span></section>;
}

export default function ProjectAppStudio(props: Props) {
  const app = projectApps.find((item) => item.id === props.appId) ?? projectApps[0];
  return <div className={`project-app-studio app-theme-${props.appId}`} data-app-theme={props.appId} style={{ "--studio-accent": app.accent } as React.CSSProperties}>
    <StudioHeader appId={props.appId} project={props.project} />
    {props.appId === "minerals" ? <MineralAtlas project={props.project} onEvidence={props.onEvidence} onOutcome={props.onOutcome} />
      : props.appId === "workforce" ? <WorkforceStudio project={props.project} onEvidence={props.onEvidence} onOutcome={props.onOutcome} />
      : props.appId === "manufacturing" ? <ManufacturingTwin project={props.project} onEvidence={props.onEvidence} onOutcome={props.onOutcome} />
      : props.appId === "logistics" ? <LogisticsRadar project={props.project} onEvidence={props.onEvidence} onOutcome={props.onOutcome} />
      : props.appId === "quality" ? <QualityGenealogy project={props.project} onEvidence={props.onEvidence} onOutcome={props.onOutcome} />
      : <UnsupportedStudio project={props.project} appId={props.appId} />}
  </div>;
}
