"use client";
import { useEffect, useMemo, useRef, useState, useSyncExternalStore, type FormEvent, type ReactNode } from "react";
import { projectApps, type ExpertAgent, type ProjectAppId, type WorkspaceProject, type WorkspaceTabId } from "./workspace-model";
import { AppGlyph } from "./VisualIdentity";
import { downloadJson } from "./SimulationStudio";
import { activateSamsung, advanceSamsung, approveSamsung, calculateSamsungPlan, changeSamsungRules, initialSamsungState, requestSamsungConnections, samsungApprovalRoles, samsungAgents, samsungBrief, samsungDelivery, samsungExport, samsungOwners, samsungPlans, samsungProjectPatch, samsungPrompts, samsungSources, samsungStress, submitSamsungPrompt, type SamsungState } from "./samsung-demo-model";
import "./analysis-workbench.css";
import "./samsung-demo.css";

// Same lifetime as the portal's onboarding drafts; navigations retain each project's run.
const sessions = new Map<string, SamsungState>();
const listeners = new Set<() => void>();
function snapshot(projectId: string) { if (!sessions.has(projectId)) sessions.set(projectId, initialSamsungState(projectId)); return sessions.get(projectId)!; }
function subscribe(listener: () => void) { listeners.add(listener); return () => { listeners.delete(listener); }; }
function mutate(projectId: string, action: (state: SamsungState) => SamsungState) { sessions.set(projectId, action(snapshot(projectId))); listeners.forEach(notify => notify()); }
const number = (n: number) => n.toLocaleString("en-US");
const dollars = (n: number) => `$${number(n)}`;
type Props = { project: WorkspaceProject; tab: WorkspaceTabId; app: ProjectAppId | null; onTab: (tab: WorkspaceTabId) => void; onOpenApp: (app: ProjectAppId) => void; onProjectChange: (id: string, patch: Partial<WorkspaceProject>) => void; onAgentsChange: (id: string, agents: readonly ExpertAgent[]) => void; canConnect: boolean; canRun: boolean; canReview: boolean };
function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="os-panel samsung-panel"><header><h2>{title}</h2></header>{children}</section>; }
function PlanMetrics({ state }: { state: SamsungState }) {
  const plan = calculateSamsungPlan(samsungPlans[state.stage >= 5 ? 3 : state.stage >= 3 ? 2 : 0], state.stage >= 4, state.rules);
  return <div className="os-metrics samsung-metrics">{[["Launch-window deliveries", `${number(plan.shipped)} / ${number(plan.demand)}`], ["Service level", `${plan.service.toFixed(2)}%`], ["Incremental cost", dollars(plan.cost)], ["Quarantined units used", "0"]].map(([label, value]) => <div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>;
}
function Evidence({ sourceId, onClose }: { sourceId: string; onClose: () => void }) {
  const source = samsungSources.find(s => s.id === sourceId)!;
  return <section className="os-panel samsung-evidence" aria-label={`${source.name} evidence`} tabIndex={-1}><header><h2>{source.name}</h2><button type="button" onClick={onClose}>Close evidence</button></header><p><b>{source.database}</b> · {source.tables} · {source.rows} synthetic source rows</p><p>{source.issue}</p><p className="os-help">Fields: {source.fields}. Canonical reference: {source.variable}. These rows are demonstration fixtures, not database query results.</p><pre>{JSON.stringify(source.sample, null, 2)}</pre></section>;
}
function PlanTable({ state, revised = false }: { state: SamsungState; revised?: boolean }) {
  const plans = revised ? [samsungPlans[2], samsungPlans[3]] : samsungPlans.slice(0, 3);
  return <div className="os-table-scroll"><table className="os-table"><thead><tr><th>Response</th><th>Delivered</th><th>Service</th><th>Incremental cost</th><th>Budget / service gates</th></tr></thead><tbody>{plans.map(p => { const r = calculateSamsungPlan(p, state.stage >= 4, state.rules); return <tr key={p.id}><th>{p.label}</th><td>{number(r.shipped)}</td><td>{r.service.toFixed(2)}%</td><td>{dollars(r.cost)}</td><td><span className={`samsung-badge ${r.feasible ? "pass" : "fail"}`}>{r.feasible ? "Pass" : "Fail"}</span></td></tr>; })}</tbody></table></div>;
}
function StressTable({ state }: { state: SamsungState }) { return <div className="os-table-scroll"><table className="os-table"><thead><tr><th>Stress case</th><th>Service</th><th>Result</th><th>Review scope</th></tr></thead><tbody>{samsungStress(state.rules).map(s => <tr key={s.label}><th>{s.label}</th><td>{s.service.toFixed(2)}%</td><td>{s.feasible ? "Pass" : "Fail"}</td><td>{s.envelope ? "Agreed single-factor test" : "Outside approved envelope; escalation required"}</td></tr>)}</tbody></table></div>; }
function ToolEvidence({ state, app, onPlayground, onEvidence }: { state: SamsungState; app: ProjectAppId; onPlayground: () => void; onEvidence: (id: string) => void }) {
  const definition = projectApps.find(a => a.id === app)!;
  if (!state.usedApps.includes(app)) return <Panel title="This app has not been used"><p>Continue the agent conversation in Playground. Apps appear here when a task actually uses them.</p><button type="button" onClick={onPlayground}>Open Playground</button></Panel>;
  const plan = calculateSamsungPlan(samsungPlans[state.stage >= 5 ? 3 : state.stage >= 3 ? 2 : 0], state.stage >= 4, state.rules);
  const traces = state.trace.filter(t => t.app === app);
  return <><header className="samsung-tool-header"><AppGlyph appId={app} /><div><p>PROJECT APP · SAMSUNG DEMO</p><h1>{definition.name}</h1></div><button type="button" onClick={onPlayground}>Back to Playground</button></header><PlanMetrics state={state} />
    {app === "optimizer" ? <Panel title="Candidate comparison"><PlanTable state={state} revised={state.stage >= 5} /><p className="os-help">Explicit candidate enumeration, not an enterprise solver. Cost and capacity checks recalculate from declared inputs.</p></Panel> : app === "simulation" ? <Panel title="Stress-test envelope"><StressTable state={state} /><p>Compound shocks can breach service. Escalate if demand exceeds the tested range or a second supply constraint fails simultaneously. These cases are deterministic, not a probability forecast.</p></Panel> : app === "flow" ? <Panel title="Incremental cost reconciliation"><div className="os-table-scroll"><table className="os-table"><thead><tr><th>Intervention</th><th>Units</th><th>USD / unit</th><th>Cost</th></tr></thead><tbody>{plan.costs.map(c => <tr key={c.label}><th>{c.label}</th><td>{number(c.units)}</td><td>{c.rate}</td><td>{dollars(c.total)}</td></tr>)}</tbody><tfoot><tr><th colSpan={3}>Total incremental cost</th><td>{dollars(plan.cost)}</td></tr></tfoot></table></div><p>Illustrative net contribution protected: {dollars(plan.netContributionProtected)} = additional deliveries versus 98,000 × $210 contribution per unit − incremental cost.</p></Panel> : app === "demand" || app === "logistics" ? <Panel title="Launch allocation and fulfilment"><div className="os-table-scroll"><table className="os-table"><thead><tr><th>Market</th><th>Demand</th><th>Launch-window allocation</th><th>Unserved</th></tr></thead><tbody>{plan.allocations.map(a => <tr key={a.market}><th>{a.market}</th><td>{number(a.requested)}</td><td>{number(a.delivered)}</td><td>{number(a.requested - a.delivered)}</td></tr>)}</tbody></table></div><p>Allocation is proportional to demand, with integer rounding reconciled to total shipments. Unserved orders remain explicit.</p></Panel> : <Panel title={app === "quality" ? "Quality and qualification controls" : "Binding capacities and dependencies"}><div className="samsung-capacities">{Object.entries(plan.capacity).map(([label, units]) => <div key={label}><span>{label}</span><strong>{number(units)}</strong><progress value={units} max={150000}>{units}</progress></div>)}</div><p>Delivered units are the minimum of demand, qualified memory, released batteries, assembly and transport capacity. The 18,000-unit battery hold stays excluded throughout.</p></Panel>}
    <Panel title="Agent activity and source evidence">{traces.map(t => <div className="samsung-trace-row" key={t.id}><b>{t.agent}</b><span>{t.text}</span>{t.evidence && <button type="button" onClick={() => onEvidence(t.evidence!)}>Inspect source ↗</button>}</div>)}</Panel></>;
}

export default function SamsungProjectWorkspace({ project, tab, app, onTab, onOpenApp, onProjectChange, onAgentsChange, canConnect, canRun, canReview }: Props) {
  const state = useSyncExternalStore(subscribe, () => snapshot(project.id), () => snapshot(project.id));
  const [prompt, setPrompt] = useState(""); const [error, setError] = useState(""); const [evidence, setEvidence] = useState<string | null>(null);
  const [paused, setPaused] = useState(false); const [budget, setBudget] = useState(String(state.rules.budget)); const [floor, setFloor] = useState(String(state.rules.serviceFloor));
  const transcript = useRef<HTMLDivElement>(null); const evidenceRef = useRef<HTMLDivElement>(null);
  const agents = useMemo(() => state.connection === "active" ? samsungAgents : [], [state.connection]);
  useEffect(() => {
    const patch = samsungProjectPatch(project, state);
    if (Object.entries(patch).some(([key, value]) => JSON.stringify(project[key as keyof WorkspaceProject]) !== JSON.stringify(value))) onProjectChange(project.id, patch);
  }, [state, project, onProjectChange]);
  useEffect(() => { onAgentsChange(project.id, agents); }, [agents, project.id, onAgentsChange]);
  useEffect(() => {
    if (paused || (!state.running && state.connection !== "validating") || (state.running && !canRun) || (state.connection === "validating" && !canConnect)) return;
    const timer = window.setTimeout(() => mutate(project.id, advanceSamsung), 850);
    return () => window.clearTimeout(timer);
  }, [state, project.id, paused, canConnect, canRun]);
  useEffect(() => { const frame = requestAnimationFrame(() => { const element = transcript.current; if (element) element.scrollTo({ top: element.scrollHeight, behavior: "smooth" }); }); return () => cancelAnimationFrame(frame); }, [state.messages.length, state.trace.length, tab]);
  useEffect(() => { if (evidence) evidenceRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [evidence]);
  const perform = (action: (current: SamsungState) => SamsungState) => { try { mutate(project.id, action); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to complete this demo action."); } };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!canRun) return; perform(current => submitSamsungPrompt(current, prompt)); setPrompt(""); };
  const nextPrompt = samsungPrompts[state.stage];
  const candidate = calculateSamsungPlan(samsungPlans[3], true, state.rules);
  const gatesPass = candidate.feasible && samsungStress(state.rules).filter(s => s.envelope).every(s => s.feasible);
  const busy = !!state.running || state.connection === "validating";
  return <div className={`project-os analysis-workbench samsung-demo ${tab === "agents" ? "samsung-playground" : ""}`} data-page-heading tabIndex={-1}>
    <header className="samsung-heading"><div><p className="samsung-eyebrow">SAMSUNG · LAUNCH CONTINUITY DEMO</p><h1>{app ? projectApps.find(a => a.id === app)?.name : tab === "agents" ? "Playground" : tab === "data" || tab === "graph" ? "Data and agent activation" : tab === "decisions" ? "Decision review" : tab === "apps" ? "Project apps" : project.name}</h1><p>{project.client} / {project.name}</p></div><div className="samsung-actions"><a href="/samsung-demo-guide.html" target="_blank" rel="noreferrer">Demo guide ↗</a><button type="button" onClick={() => downloadJson(samsungExport(state), `${project.id}-samsung-demo.json`)}>Export demo record</button></div></header>
    <div className="samsung-boundary"><span className="samsung-badge">Demo runtime</span><span>Simulated databases, worker, agents and execution · current browser session only</span></div>
    {error && <p className="os-notice warning" role="alert">{error}</p>}
    {app ? <ToolEvidence state={state} app={app} onPlayground={() => onTab("agents")} onEvidence={setEvidence} /> : tab === "apps" ? <><Panel title={state.usedApps.length ? "Apps used in this project" : "Your new project starts with Playground"}><p>Specialist apps join this list and the app bar only when an agent uses them. Connecting data or reading the scope does not add apps.</p><div className="samsung-app-grid"><button type="button" className="samsung-app-card" onClick={() => onTab("agents")}><AppGlyph appId="playground" /><b>Playground</b><span>Open the agent conversation →</span></button>{state.usedApps.map(id => <button className="samsung-app-card" type="button" key={id} onClick={() => onOpenApp(id)}><AppGlyph appId={id} /><b>{projectApps.find(a => a.id === id)?.name}</b><span>Inspect agent work →</span></button>)}</div></Panel>{state.connection !== "active" && <button className="os-primary" type="button" onClick={() => onTab("data")}>Connect demo data and activate agents →</button>}</> : tab === "data" || tab === "graph" ? <>
      <Panel title="1. Configure the customer-side demo worker"><p>The scenario represents a worker inside Samsung’s environment reading approved databases and returning project-scoped evidence to the portal. This demo performs that sequence locally.</p><label>Demo worker name<input value={state.worker} disabled={state.connection !== "empty" || !canConnect} onChange={e => perform(s => ({ ...s, worker: e.target.value }))} /></label><p className="os-help">Use the supplied .invalid name. No credentials are requested and no network request is made.</p><div className="samsung-source-grid">{samsungSources.map((source, i) => <label className="samsung-source-card" key={source.id} aria-label={source.name}><input type="checkbox" checked={state.selectedSources.includes(source.id)} disabled={state.connection !== "empty" || !canConnect} onChange={e => perform(s => ({ ...s, selectedSources: e.target.checked ? [...s.selectedSources, source.id] : s.selectedSources.filter(id => id !== source.id) }))} /><span><b>{source.name}</b><code>{source.database}</code><small>{source.tables}</small><em>{state.connection === "active" ? "Demo feed active" : state.connection === "validated" || state.connectionTick > i ? "Fixture check passed" : "Not validated"}</em></span></label>)}</div><label className="os-checkbox"><input type="checkbox" checked={state.readOnly} disabled={state.connection !== "empty" || !canConnect} onChange={e => perform(s => ({ ...s, readOnly: e.target.checked }))} />Allow only read-only demo queries; retain evidence within this project.</label><div className="samsung-actions"><button type="button" disabled={state.connection !== "empty" || !canConnect} onClick={() => perform(s => ({ ...s, selectedSources: samsungSources.map(source => source.id) }))}>Select four demo sources</button><button type="button" className="os-primary" disabled={state.connection !== "empty" || !canConnect} onClick={() => perform(requestSamsungConnections)}>Validate connections (demo)</button></div>{state.connection === "validating" && <div role="status"><progress max={4} value={state.connectionTick} /> Checking fixture schemas and read-only scope…</div>}</Panel>
      {state.connection !== "empty" && state.connection !== "validating" && <Panel title="2. Review fields and activate agents"><div className="os-table-scroll"><table className="os-table"><thead><tr><th>Source</th><th>Available fields</th><th>Variable reference</th><th>Evidence</th></tr></thead><tbody>{samsungSources.map(s => <tr key={s.id}><th>{s.name}</th><td>{s.fields}</td><td>{s.variable}</td><td><button type="button" onClick={() => setEvidence(s.id)}>Inspect sample</button></td></tr>)}</tbody></table></div><p className="os-notice warning">Quality exception: 18,000 batteries are quarantined. The agent contract excludes them from every candidate.</p><label className="os-checkbox"><input type="checkbox" checked={state.mapped} disabled={state.connection === "active" || !canConnect} onChange={e => perform(s => ({ ...s, mapped: e.target.checked }))} />I reviewed units, fields, source scope and the quarantine exclusion.</label><div className="samsung-actions"><button type="button" className="os-primary" disabled={state.connection === "active" || !canConnect} onClick={() => perform(activateSamsung)}>{state.connection === "active" ? "Demo agents active" : "Activate demo agents"}</button>{state.connection === "active" && <button type="button" onClick={() => onTab("agents")}>Open Playground →</button>}</div><p className="os-help">Activation enables the project’s {samsungAgents.length} demo specialist identities. No server process is installed.</p></Panel>}
    </> : tab === "agents" ? <>
      <div className="samsung-chat-layout"><section className="samsung-console"><header><b>Samsung Project Orchestrator</b><span>{state.connection === "active" ? busy ? paused ? "Paused" : "Agents working" : "Ready" : "Awaiting data activation"}</span></header><div className="samsung-transcript" ref={transcript} aria-live="polite" aria-relevant="additions"><article className="samsung-message agent"><small>Project Orchestrator · demo</small><p>Welcome to {project.name}. {state.connection === "active" ? "Start with the scope prompt below. I will select specialist apps as the work requires them." : "Connect the four demo data sources and activate the worker in Data. This project has no used apps yet."}</p>{state.connection !== "active" && <button type="button" onClick={() => onTab("data")}>Set up demo data</button>}</article>{state.messages.map(message => <article className={`samsung-message ${message.role}`} key={message.id}><small>{message.author}</small><p>{message.text}</p>{message.refs.length > 0 && <div className="samsung-evidence-links">{message.refs.map(id => <button type="button" key={id} onClick={() => setEvidence(id)}>{samsungSources.find(s => s.id === id)?.name} ↗</button>)}</div>}</article>)}{state.running && <article className="samsung-message agent" role="status"><small>{state.running.tasks[state.running.index].agent} · {paused ? "paused" : "working"}</small><p>{state.running.tasks[state.running.index].text}</p><progress max={state.running.tasks.length} value={state.running.index} /></article>}</div><form className="samsung-composer" onSubmit={submit}><label htmlFor="samsung-prompt">Message the project agents</label><textarea id="samsung-prompt" rows={3} value={prompt} disabled={busy || !canRun} onChange={e => setPrompt(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); e.currentTarget.form?.requestSubmit(); } }} placeholder="Paste the next prompt from the demo guide…" /><div className="samsung-actions"><span>Enter to send · Shift+Enter for a new line</span><button type="submit" className="os-primary" disabled={!prompt.trim() || busy || !canRun}>Send message ↑</button></div></form></section><aside className="samsung-activity"><Panel title="Agent activity"><p className="os-help">Each completed task records the source it inspected. Its app then appears in the bar.</p>{!state.trace.length && <p>No specialist tasks yet.</p>}{state.trace.map(t => <div className="samsung-task" key={t.id}><small>{t.agent}</small><p>{t.text}</p>{t.app && <button type="button" onClick={() => onOpenApp(t.app!)}>{projectApps.find(a => a.id === t.app)?.name} ↗</button>}</div>)}{state.running && <button type="button" onClick={() => setPaused(!paused)}>{paused ? "Resume agent run" : "Pause agent run"}</button>}</Panel></aside></div>
      {nextPrompt && <Panel title={nextPrompt.title}><p>{nextPrompt.prompt}</p><div className="samsung-actions"><button type="button" disabled={busy} onClick={() => setPrompt(nextPrompt.prompt)}>Use this prompt</button>{state.stage === 6 && <button type="button" onClick={() => onTab("decisions")}>Complete human review →</button>}</div></Panel>}
      {state.stage >= 2 && <PlanMetrics state={state} />}
      {state.decision === "executed" && <Monitoring state={state} onAdvance={() => { if (canRun) perform(s => ({ ...s, executionDay: Math.min(10, s.executionDay + 1) })); }} canAdvance={canRun} />}
    </> : tab === "decisions" ? <>
      {state.stage < 3 ? <Panel title="No decision package yet"><p>Ask the agents to diagnose the crisis and compare candidate responses in Playground.</p><button type="button" onClick={() => onTab("agents")}>Open Playground</button></Panel> : <><PlanMetrics state={state} /><Panel title="Decision constraints"><div className="samsung-form-grid"><label>Incremental budget · USD<input type="number" min="0" value={budget} disabled={busy || !canReview} onChange={e => setBudget(e.target.value)} /></label><label>Minimum service · %<input type="number" min="0.1" max="100" step="0.1" value={floor} disabled={busy || !canReview} onChange={e => setFloor(e.target.value)} /></label><button type="button" disabled={busy || !canReview} onClick={() => { if (!budget.trim() || !floor.trim()) { setError("Enter both constraint values."); return; } perform(s => changeSamsungRules(s, { budget: Number(budget), serviceFloor: Number(floor) })); }}>Apply constraints and invalidate review</button></div><p className="os-help">Changing either limit removes approvals and any release state. A new decision brief is required.</p></Panel><Panel title="Candidate and revised response"><PlanTable state={state} revised={state.stage >= 5} /></Panel>{state.stage >= 5 && <><Panel title="Risk envelope"><StressTable state={state} /></Panel><Panel title="Human review and sign-off"><p>Three separate role attestations are required. In this demonstration, you act as each reviewer. These are local review records, not authenticated enterprise approvals.</p><p className={`os-notice ${gatesPass ? "" : "warning"}`}>Current gates: budget {candidate.budgetPass ? "PASS" : "FAIL"}, service {candidate.servicePass ? "PASS" : "FAIL"}, qualification {candidate.qualifiedPass ? "PASS" : "FAIL"}, agreed stress envelope {gatesPass ? "PASS" : "FAIL"}.</p>{samsungApprovalRoles.map(role => <div className="samsung-approval" key={role}><div><b>{role}</b><p>{role === "Quality owner" ? "Accept released-lot evidence and preserve quarantine." : role === "Finance controller" ? "Accept itemized costs and the budget ceiling." : "Accept market allocations and the disclosed combined-shock escalation trigger."}</p></div><button type="button" disabled={!canReview || busy || state.stage < 6 || !gatesPass || state.approvals.includes(role) || state.decision === "executed"} onClick={() => perform(s => approveSamsung(s, role))}>{state.approvals.includes(role) ? "Sign-off recorded" : `Simulate ${role} sign-off`}</button></div>)}{state.stage < 6 && <p role="status">Send the “Prepare human review” prompt before recording approvals.</p>}<button type="button" className="os-primary" onClick={() => onTab("agents")}>Return to Playground {state.decision === "approved" ? "to simulate release" : "for the next prompt"} →</button></Panel></>}{state.decision === "executed" && <Monitoring state={state} onAdvance={() => { if (canRun) perform(s => ({ ...s, executionDay: Math.min(10, s.executionDay + 1) })); }} canAdvance={canRun} />}</>}
    </> : tab === "governance" ? <Panel title="Demo controls and production boundaries"><p>{samsungBrief.boundary}</p><ul><li>Four read-only source contracts must be validated before activation.</li><li>Apps are recorded only when an agent task uses them.</li><li>Quarantined stock and unqualified supply are excluded.</li><li>Changed constraints or shocks invalidate review.</li><li>Three explicit role sign-offs precede simulated release.</li><li>Refresh starts a new portal session; export the record before closing the demo.</li></ul><button type="button" onClick={() => downloadJson(samsungExport(state), `${project.id}-audit.json`)}>Export audit record</button></Panel> : <>
      <Panel title={state.connection === "active" ? "Your launch decision workspace" : "An empty project, ready for its first conversation"}><p>{samsungBrief.problem}</p><p>{samsungBrief.outcome}</p><div className="samsung-path"><span>1 · Connect data</span><span>2 · Activate agents</span><span>3 · Ask in Playground</span><span>4 · Review and simulate</span></div><div className="samsung-actions"><button type="button" className="os-primary" onClick={() => onTab(state.connection === "active" ? "agents" : "data")}>{state.connection === "active" ? "Continue in Playground" : "Connect demo data"} →</button><button type="button" onClick={() => onTab("apps")}>View project apps ({state.usedApps.length + 1})</button></div></Panel>
      <div className="os-metrics"><div><small>Data worker</small><strong>{state.connection === "active" ? "Active · demo" : "Not active"}</strong></div><div><small>Specialist apps used</small><strong>{state.usedApps.length}</strong></div><div><small>Agent tasks completed</small><strong>{state.trace.length}</strong></div><div><small>Human sign-offs</small><strong>{state.approvals.length} / 3</strong></div></div>{state.stage >= 2 && <PlanMetrics state={state} />}
    </>}
    {evidence && <div ref={evidenceRef}><Evidence sourceId={evidence} onClose={() => setEvidence(null)} /></div>}
  </div>;
}
function Monitoring({ state, onAdvance, canAdvance }: { state: SamsungState; onAdvance: () => void; canAdvance: boolean }) {
  const delivered = samsungDelivery(state.executionDay);
  return <Panel title="Simulated execution and monitoring"><div className="samsung-monitor"><div><small>Demo clock</small><strong>Day {state.executionDay} / 10</strong></div><div><small>Delivered so far</small><strong>{number(delivered)}</strong></div><div><small>Remaining committed deliveries</small><strong>{number(128000 - delivered)}</strong></div></div><progress max={128000} value={delivered} aria-label="Simulated deliveries" /><div className="samsung-actions"><button className="os-primary" type="button" disabled={!canAdvance || state.executionDay >= 10} onClick={onAdvance}>Advance one demo day →</button><span>{state.executionDay < 10 ? "Time advances only when you click; this is a replay ledger." : "Simulation complete. 128,000 delivered; 4,000 remain unserved."}</span></div><div className="os-table-scroll"><table className="os-table"><thead><tr><th>Window</th><th>Owner</th><th>Action / evidence</th></tr></thead><tbody>{samsungOwners.map(o => <tr key={o.day}><th>{o.day}</th><td>{o.owner}</td><td>{o.action}</td></tr>)}</tbody></table></div><p>Final plan: 96.97% service, $898,000 incremental cost, $2,000 budget headroom, zero quarantined units used. Escalate if the combined demand-and-transport trigger occurs. No live operational instruction was sent.</p></Panel>;
}
